### ISSUE TITLE
[WIP] Update Dragonfly > v1.3.0

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#203]
Dragonfly has fix resp3 issue with PUBSUB

**Comment by FZambia** [comment]
Tested Dragonfly v1.2.0 - works for me without forcing RESP2.

**Comment by rueian** [comment]
It turns out that `AlwaysRESP2` is still required for dragonfly <= v1.2.1 because it doesn't support HELLO AUTH: https://github.com/rueian/rueidis/issues/207

I have contributed to dragonfly https://github.com/dragonflydb/dragonfly/pull/1156 to support that. Hopefully, `AlwaysRESP2` won't be necessary with newer versions.

**Comment by rueian** [comment]
Dragonfly 1.3.0 is out, however, we still can't use PUBSUB on it because there is an out-of-order issue: https://github.com/dragonflydb/dragonfly/issues/1245.

**Comment by gaby** [comment]
@rueian Is this fix now that the dragonfly issue was closed?

**Comment by rueian** [comment]
Hi @gaby, the dragonfly issue was closed but they haven't released it yet.

**Comment by gaby** [comment]
> Hi @gaby, the dragonfly issue was closed but they haven't released it yet.

Thanks!
