### ISSUE TITLE
Support CLIENT NO-EVICT/NO-TOUCH/SETINFO

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#236]
As titled. These three commands are introduced in Redis 7.2 and needed to be supported in the `rueidis.ClientOption` struct.

**Comment by SoulPancake** [comment]
Let me know if I can collab @mingdaoy

**Comment by mingdaoy** [comment]
@SoulPancake would you like to take CLIENT NO-TOUCH command?

**Comment by SoulPancake** [comment]
Sure @mingdaoy
