### ISSUE TITLE
Are Lua script Exec calls pipelined?

### ISSUE THREAD

**Issue by salarali** [redis/rueidis#242]

**Comment by salarali** [comment]
But basically there shouldnt be any difference between just running the lua script and manually pipelining using ExecMulti, in terms of getting the benefits of auto pipelining feature.

**Comment by rueian** [comment]
No, there shouldn’t be big difference.

ExecMulti is just a convenient way to pipeline those invocations in case of you don’t have existing goroutines to make concurrent requests.

**Comment by salarali** [comment]
Thanks.
