### ISSUE TITLE
Missing Go 1.18 build for v1.0.3

### ISSUE THREAD

**Issue by epps** [redis/rueidis#243]
## Context

I tried to install v1.0.3 for Go v1.18 by running the following in the terminal:

```shell
go get github.com/redis/rueidis@v1.0.3-go1.18
```

OS: macOS Monterey 12.5.1 (Apple M1)
Go version: 1.18.10

## Error

```text
go: github.com/redis/rueidis@v1.0.3-go1.18: invalid version: unknown revision v1.0.3-go1.18
```

I was able to install v1.0.2 with the `-go1.18` build tag, so I'm assuming the issue is purely a missing build.

**Comment by rueian** [comment]
Hi @epps,

I am sorry about that. Please use  `go get github.com/redis/rueidis@v1.0.4-go1.18` instead.

**Comment by epps** [comment]
Hi, @rueian!

No worries. It wasn't a blocker as much as something I thought might helpful to bring to someone's attention. I appreciate the speedy reply and the guidance. Thank you for all your work!
