### ISSUE TITLE
product ready?

### ISSUE THREAD

**Issue by shaolei** [redis/rueidis#244]
product ready?

**Comment by rueian** [comment]
Sure

**Comment by rueian** [comment]
Yes, it will add a little overhead.

**Comment by rueian** [comment]
Hi @shaolei, do you still have other concerns?

**Comment by shaolei** [comment]
> Hi @shaolei, do you still have other concerns?

I am currently planning to use Google Memory Store for Redis, which has a read-only replica node. Is it a cluster?
Does it seem to not support client-side caching, which will affect the performance of the rueidislock?

**Comment by rueian** [comment]
Hi @shaolei,

Unfortunately, Google Memory Store is not a cluster and does not support client-side caching.

Furthermore, rueidislock can't work without client-side caching.

**Comment by da-tai** [comment]
Does this work on Redis Enterprise?

**Comment by shaolei** [comment]
> 



> Hi @shaolei,
> 
> Unfortunately, Google Memory Store is not a cluster and does not support client-side caching.
> 
> Furthermore, rueidislock can't work without client-side caching.

Which library should I use when using redislock  with rueidis?

**Comment by rueian** [comment]
I recommend you use rueidislock with a standard Redis cluster instead of Google Memory Store.

You may also consider using the https://github.com/go-redsync/redsync, though it depends on an old rueidis version which is not recommended.

**Comment by rueian** [comment]
> Does this work on Redis Enterprise?

Hi @da-tai, rueidis works with Redis Enterprise with client-side caching disabled.

**Comment by shaolei** [comment]
> I recommend you use rueidislock with a standard Redis cluster instead of Google Memory Store.
> 
> You may also consider using the https://github.com/go-redsync/redsync, though it depends on an old rueidis version which is not recommended.

Thank you for your suggestion.
Our company is currently using Google memory store, and I am currently unable to use other Redis services.
Perhaps I can fork the redsync library and implement it with the latest rueidis, i will try it.

**Comment by rueian** [comment]
Hey @shaolei, rueidislock v1.0.6 can work without client-side caching now!

**Comment by shaolei** [comment]
> Hey @shaolei, rueidislock v1.0.6 can work without client-side caching now!

good job, I will try it.

**Comment by shaolei** [comment]
@rueian Does the sentinel readonly replica feature support Google memory store for Redis?

**Comment by rueian** [comment]
No. As far as I know, Google Memory Store doesn’t support Redis Sentinel.
