### ISSUE TITLE
Expiration time idea

### ISSUE THREAD

**Issue by ash2k** [redis/rueidis#266]
I think it may be more convenient and type-safe to provide expiration time as `time.Duration` (for `EX`/`PX`) or `time.Time` (for `EXAT`/`PXAT`). Just convert to milliseconds and use the value.

**Comment by rueian** [comment]
Hi @ash2k,

Thank you for your suggestions. I would much prefer doing that with helpers, for example:
```go
c.B().Set().Key("k").Value("v").ExSeconds(rueidis.Sec(time.Now()))
```
I believe this way will make the API very clear and be no room for wondering whether it converts to other precision like microseconds.

We have actually done a similar thing here: https://github.com/redis/rueidis/blob/45b2008fb313b16110d304b50c8af11b04238083/rueidiscompat/adapter.go#L819-L823

Maybe we can just expose those helpers from `rueidis`.

**Comment by ash2k** [comment]
I don't think there is much value in helpers as the same can be done with just methods on `Duration` and `Time`. The whole point (type safety and ease of use) is lost when in the end user still needs to provide an `int64`. People who care how exactly the method works can read it's docs (it can explain that what resolution it uses) or code.

Type safety is important as some methods/commands accept seconds and some milliseconds and it's easy to use a wrong helper for a wrong resolution (but the same type) and not notice.

**Comment by SoulPancake** [comment]
I can take this migration up if required ^_^

**Comment by rueian** [comment]
> I can take this migration up if required ^_^

Hi @SoulPancake, this should be done by adding new functions instead of a migration.

**Comment by rueian** [comment]
Hi @ash2k,

Thanks to @HoganEdwardChu (https://github.com/redis/rueidis/pull/267), we will be able to do this in the next version:

```go
client.B().Set().Key("k").Value("v").Ex(time.Second).Build()
client.B().Set().Key("k").Value("v").Exat(time.Now()).Build()
client.B().Set().Key("k").Value("v").Px(time.Second).Build()
client.B().Set().Key("k").Value("v").Pxat(time.Now()).Build()
```

Does it make sense to you?

**Comment by ash2k** [comment]
Hi @rueian! Yes, this is perfect, thank you!
