### ISSUE TITLE
RedisJSON

### ISSUE THREAD

**Issue by fourfire** [redis/rueidis#269]
Does rueidis have a example for RedisJSON ?

**Comment by rueian** [comment]
Sure. What kind of examples you are looking for?

**Comment by rueian** [comment]
You may find some examples here:
https://github.com/redis/rueidis/issues/67
https://github.com/redis/rueidis/issues/181

**Comment by rueian** [comment]
Hi @fourfire, do you still need help?

**Comment by fourfire** [comment]
No, thanks

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年6月1日 20:27
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [redis/rueidis] RedisJSON (Issue #269)


Hi @fourfire<https://github.com/fourfire>, do you still need help?

―
