### ISSUE TITLE
Confusing Type Error Messages When Using As* and To* methods on RedisMessage and RedisResult

### ISSUE THREAD

**Issue by kevinxmorales** [redis/rueidis#271]
When using RedisMessage methods like AsMap or ToArray, there can be confusing error messages that result from a no-op type conversion. 
For example, rueidis does not have a way for me to convert a geosearch query into a GeoLocation struct the way go-redis does, but I figured I might be able to get a map with the coords, dist, and hash. So I tried the following
```golang
resp = client.Do(context.Background(), client.B().
	Geosearch().
	Key("cities").
	Fromlonlat(77.6088, 43.1566).
	Bybox(500.0).
	Height(500.0).
	Mi().
	Withcoord().Withdist().Withhash().
	Build())
geoArr, err := resp.ToArray()
if err != nil {
        return err
}
for _, v := range geoArr {
	x, err := v.AsMap()
	if err != nil {
		log.Fatal(err)
	}
}
``` 
Trying to run this results in a panic with an error message 
```
panic: redis message type : as map key is not supported
```

I understand the need to reject bad type conversions, however error messages that use symbols like ':' to represent types are hard to understand. I had to look into the source code to find out that ':' means int64
From message.go
```golang
func (m *RedisMessage) IsInt64() bool {
	return m.typ == ':'
}
```

Could there be a way to swap in a string that describes the type in these messages instead of seeing a symbol?
The above error message could instead be 
```
panic: redis message type int64 as map key is not supported
```

Maybe there be a way to keep all these symbols as constants and have a map that maps the symbol to the string representation of the type? That way the panic can just reference the symbol map and sub in the type
```go
var (
	i64 = byte(':')
	f64 = byte(',')

	types = map[byte]string{
		i64: "int64",
		f64: "float64",
		// more types below
	}
)
```
```golang
//Then in code use
func (m *RedisMessage) IsInt64() bool {
	return m.typ == types[i64]
}
```
```golang
//Then in error message
panic(fmt.Sprintf("redis message type %s as map key is not supported", types[typ]))
```

If this is deemed actionable I would be interested in implementing the solution to this

**Comment by rueian** [comment]
Hi @kevinxmorales,

Thank you for your suggestions. It sounds like a good idea.

> If this is deemed actionable I would be interested in implementing the solution to this

Many thanks. Your PR will be very welcome. I would suggest putting the proposed `types` in `resp.go` file and somewhere closed these:
https://github.com/redis/rueidis/blob/71bd05fa79b2378b573a1dde4f15eff21364fd75/resp.go#L18-L35

> For example, rueidis does not have a way for me to convert a geosearch query into a GeoLocation struct the way go-redis does

BTW, would you also be willing to add an `AsGeosearch` helper to `rueidis.RedisResult`? Like we already have an `AsFtsearch` helper and we also already have a similar implementation in `rueidiscompat`: https://github.com/redis/rueidis/blob/71bd05fa79b2378b573a1dde4f15eff21364fd75/rueidiscompat/command.go#L2149-L2210

**Comment by kevinxmorales** [comment]
Great, I'll get starting looking into the solutions to both of these. Thanks!
