### ISSUE TITLE
Performance issue for bulk MGETs 

### ISSUE THREAD

**Issue by smf8** [redis/rueidis#278]
Hello, after testing Rueidis in our production setup we faced noticable performance issues in Rueidis clients.

## Use case: 
We're using redis (**sentinel setup**) to cache user metadata with userID as the key. we have around **600MB** worth of data in redis.

Each request consists of a batch of userIDs (**size varies between 50-300**) for which we perform an `MGET` command to get the metadata.
request rate is around **1.5K RPS**.

With go-redis, there is a considerable load on Redis but 99th percentile of latency is **under 50ms.**

But as for rueidis, the total number of queries sent to redis decreased by 70% but 99th percentile of latency has increased to **160ms**
 followed by more than 20% CPU usage.

![image](https://github.com/redis/rueidis/assets/14906511/47e3d479-3344-4bd1-afc2-d9a8d38ce767)

As I've investigated with some benchmarks. This is mainly due to the design of `parallelMGetCache` which is splitting keys and again merging the result which is unnecessary for `single` and `sentinel` clients.

The only solution to the performance issue was to use `MGet` directly (not with the helper function) which will cause cache entry duplication.

## Possible Solution
I think moving the cache to `Client` level will be a good idea for `single` and `sentinel` clients. As for the requirement to flush the data in case of connection failure, we can do so by mapping cache entries from key + slot to value and flushing a subset of the cache in case any connection for a specific slot is lost.

But this will require heavy changes in the library. Can you think of any other solution?

**Comment by rueian** [comment]
Hi @smf8,

I guess the latencies come from capped `concurrency` used here:
https://github.com/redis/rueidis/blob/62f2ced49e5a134b23b57e39c799e5cbc07d3b3f/internal/util/parallel.go#L26-L29

The capped `concurrency` is likely going to make your batch of userIDs complete after many turns. Is that the same as your observation?

If that is the case, I propose to make `rueidis.MGetCache` first grouping multiple `GET`s by mapping their key slot to the underlying `pipe` and pipelining them into the `pipe.DoMultiCache`.

**Comment by smf8** [comment]
Hi @rueian 

Thank you, I'll try to write a benchmark to reproduce the scenario but I've been kind of busy. I'll update the issue as soon as it's ready.

**Comment by smf8** [comment]
You can run the following benchmark to confirm MGET helper functions are having very poor performance.

## Benchmark 
[Benchmark Link](https://gist.github.com/smf8/6a3613d7263af904795cb00532626a9d)

**Important note**: This benchmark is using `singleClient` for rueidis which will cause `rueidis.MGet` to [behave differently](https://github.com/redis/rueidis/blob/main/helper.go#L26) from the original `sentinel` setup. So if you want to rerun the benchmark, use a different type of client OR I've changed rueidis client locally with go workspace.

## Result

I've limited benchmark cpu to only 1 core to simulate my production setup. performance is increased in multi core tests.

```go
go test -count 10 -bench=. -cpu 1 -benchmem -benchtime=5s .
```
<details>
  <summary>Full result

MGetCache test duration decreases drastically because the cache is being filled gradually
</summary>
  
 ```text
go test -count 10 -bench=. -cpu 1 -benchmem -benchtime=5s .
goos: linux
goarch: amd64
pkg: test_rueidis
cpu: AMD Ryzen 7 5800X 8-Core Processor             
BenchmarkClients/rueidis.MGetCache         	     757	   6887295 ns/op	  515032 B/op	    4188 allocs/op
BenchmarkClients/rueidis.MGetCache         	    1016	   5585702 ns/op	  417494 B/op	    3257 allocs/op
BenchmarkClients/rueidis.MGetCache         	    2596	   2020004 ns/op	  178310 B/op	    1139 allocs/op
BenchmarkClients/rueidis.MGetCache         	    3694	   1768076 ns/op	  172994 B/op	    1089 allocs/op
BenchmarkClients/rueidis.MGetCache         	    3868	   1711640 ns/op	  166468 B/op	    1023 allocs/op
BenchmarkClients/rueidis.MGetCache         	    3564	   1702559 ns/op	  170245 B/op	    1061 allocs/op
BenchmarkClients/rueidis.MGetCache         	    3580	   1601249 ns/op	  166646 B/op	    1024 allocs/op
BenchmarkClients/rueidis.MGetCache         	    4167	   1979993 ns/op	  166950 B/op	    1027 allocs/op
BenchmarkClients/rueidis.MGetCache         	    3534	   1675262 ns/op	  167868 B/op	    1036 allocs/op
BenchmarkClients/rueidis.MGetCache         	    4269	   1977947 ns/op	  166584 B/op	    1023 allocs/op
BenchmarkClients/rueidis.MGet              	    1368	   4508349 ns/op	  144215 B/op	     616 allocs/op
BenchmarkClients/rueidis.MGet              	    1222	   4235525 ns/op	  144198 B/op	     615 allocs/op
BenchmarkClients/rueidis.MGet              	    1238	   4305098 ns/op	  144050 B/op	     615 allocs/op
BenchmarkClients/rueidis.MGet              	    1400	   4197005 ns/op	  144151 B/op	     615 allocs/op
BenchmarkClients/rueidis.MGet              	    1399	   4460737 ns/op	  144082 B/op	     615 allocs/op
BenchmarkClients/rueidis.MGet              	    1426	   4298869 ns/op	  144104 B/op	     614 allocs/op
BenchmarkClients/rueidis.MGet              	    1276	   4558984 ns/op	  144049 B/op	     614 allocs/op
BenchmarkClients/rueidis.MGet              	    1162	   4631517 ns/op	  144053 B/op	     614 allocs/op
BenchmarkClients/rueidis.MGet              	    1135	   5245544 ns/op	  144043 B/op	     614 allocs/op
BenchmarkClients/rueidis.MGet              	    1309	   4475865 ns/op	  143985 B/op	     613 allocs/op
BenchmarkClients/rueidis.Do(MGET)          	   10000	    517666 ns/op	   72461 B/op	     297 allocs/op
BenchmarkClients/rueidis.Do(MGET)          	   13539	    450802 ns/op	   72192 B/op	     295 allocs/op
BenchmarkClients/rueidis.Do(MGET)          	   12465	    418140 ns/op	   71874 B/op	     293 allocs/op
BenchmarkClients/rueidis.Do(MGET)          	   10000	    506228 ns/op	   71706 B/op	     292 allocs/op
BenchmarkClients/rueidis.Do(MGET)          	   12577	    420493 ns/op	   71422 B/op	     290 allocs/op
BenchmarkClients/rueidis.Do(MGET)          	   12112	    442967 ns/op	   71090 B/op	     288 allocs/op
BenchmarkClients/rueidis.Do(MGET)          	   12146	    443370 ns/op	   70801 B/op	     287 allocs/op
BenchmarkClients/rueidis.Do(MGET)          	   10000	    502355 ns/op	   70633 B/op	     286 allocs/op
BenchmarkClients/rueidis.Do(MGET)          	   10000	    503035 ns/op	   70498 B/op	     285 allocs/op
BenchmarkClients/rueidis.Do(MGET)          	   12032	    437067 ns/op	   70224 B/op	     283 allocs/op
BenchmarkClients/rueidis.DoCache(MGET)     	    4290	   1384350 ns/op	  242328 B/op	    1772 allocs/op
BenchmarkClients/rueidis.DoCache(MGET)     	    4382	   1175629 ns/op	  239415 B/op	    1750 allocs/op
BenchmarkClients/rueidis.DoCache(MGET)     	    4959	   1192404 ns/op	  235630 B/op	    1720 allocs/op
BenchmarkClients/rueidis.DoCache(MGET)     	    5224	   1145249 ns/op	  235674 B/op	    1721 allocs/op
BenchmarkClients/rueidis.DoCache(MGET)     	    5024	   1140328 ns/op	  237476 B/op	    1736 allocs/op
BenchmarkClients/rueidis.DoCache(MGET)     	    5541	   1046235 ns/op	  236020 B/op	    1723 allocs/op
BenchmarkClients/rueidis.DoCache(MGET)     	    5110	   1069736 ns/op	  235031 B/op	    1715 allocs/op
BenchmarkClients/rueidis.DoCache(MGET)     	    5476	   1131497 ns/op	  236800 B/op	    1729 allocs/op
BenchmarkClients/rueidis.DoCache(MGET)     	    4791	   1048856 ns/op	  234424 B/op	    1709 allocs/op
BenchmarkClients/rueidis.DoCache(MGET)     	    5150	   1076328 ns/op	  235332 B/op	    1703 allocs/op
BenchmarkClients/go-redis.MGET             	   14566	    391779 ns/op	   67313 B/op	     854 allocs/op
BenchmarkClients/go-redis.MGET             	   15225	    375865 ns/op	   66926 B/op	     850 allocs/op
BenchmarkClients/go-redis.MGET             	   14192	    373183 ns/op	   66542 B/op	     846 allocs/op
BenchmarkClients/go-redis.MGET             	   17518	    389567 ns/op	   66138 B/op	     842 allocs/op
BenchmarkClients/go-redis.MGET             	   15229	    387725 ns/op	   65720 B/op	     837 allocs/op
BenchmarkClients/go-redis.MGET             	   15354	    376666 ns/op	   65346 B/op	     833 allocs/op
BenchmarkClients/go-redis.MGET             	   15908	    378409 ns/op	   64950 B/op	     829 allocs/op
BenchmarkClients/go-redis.MGET             	   16393	    375138 ns/op	   64566 B/op	     825 allocs/op
BenchmarkClients/go-redis.MGET             	   17546	    388412 ns/op	   64149 B/op	     821 allocs/op
BenchmarkClients/go-redis.MGET             	   16616	    378318 ns/op	   63765 B/op	     817 allocs/op
```
</details>

<details open>
  <summary>Compact Result with benchstat</summary>
  
  
  ```text
  goos: linux
  goarch: amd64
  pkg: test_rueidis
  cpu: AMD Ryzen 7 5800X 8-Core Processor
                                │ benchstat.txt │
                                │    sec/op     │
  Clients/rueidis.MGetCache       1.873m ± 198%
  Clients/rueidis.MGet            4.468m ±   5%
  Clients/rueidis.Do(MGET)        447.1µ ±  13%
  Clients/rueidis.DoCache(MGET)   1.136m ±   8%
  Clients/go-redis.MGET           378.4µ ±   3%
  geomean                         1.100m
  
                                │ benchstat.txt  │
                                │      B/op      │
  Clients/rueidis.MGetCache       165.1Ki ± 147%
  Clients/rueidis.MGet            140.7Ki ±   0%
  Clients/rueidis.Do(MGET)        69.59Ki ±   1%
  Clients/rueidis.DoCache(MGET)   230.3Ki ±   2%
  Clients/go-redis.MGET           64.00Ki ±   2%
  geomean                         119.0Ki
  
                                │ benchstat.txt │
                                │   allocs/op   │
  Clients/rueidis.MGetCache       1.048k ± 211%
  Clients/rueidis.MGet             614.5 ±   0%
  Clients/rueidis.Do(MGET)         289.0 ±   2%
  Clients/rueidis.DoCache(MGET)   1.722k ±   2%
  Clients/go-redis.MGET            835.0 ±   2%
  geomean                          768.3
  ```
</details>

**Comment by smf8** [comment]
> The capped `concurrency` is likely going to make your batch of userIDs complete after many turns. Is that the same as your observation?

Yes exactly, The fact that for a `300` batch MGET, 300 sequential separate commands are issued will cause this behavior. 

Apart from your suggested solution. Can't batch MGet Keys be based on pipe number instead of slot?

If we have access to `multiplex` number in `helper.go`, we can change the mapping from `slot -> CMD` to `pipeNumber -> CMD`. This will solve the problem for sentinel and single clients since `pipeNumber = cmd.Slot() & (len(wire) - 1)`.

I've tested this scenario and it achieved more than 10X better performance.

```go
func MGetCache(client Client, ctx context.Context, ttl time.Duration, keys []string) (ret map[string]RedisMessage, err error) {
	if len(keys) == 0 {
		return make(map[string]RedisMessage), nil
	}
	switch client.(type) {
	case *singleClient:
		if mux, ok := client.(*singleClient).conn.(*mux); ok {
			//return parallelMGet(client, ctx, cmds.MGets(keys), keys)
			return parallelMGet(client, ctx, cmds.WireMGets(len(mux.wire), keys), keys)
		}
	}
	return parallelMGetCache(client, ctx, ttl, cmds.MGets(keys), keys)
}
```

and

```go 
func WireMGets(wires int, keys []string) map[uint16]Completed {
	return wireSlotMCMDs(wires, "MGET", keys, mtGetTag)
}

func wireSlotMCMDs(wires int, cmd string, keys []string, cf uint16) map[uint16]Completed {
	ret := make(map[uint16]Completed, 8)
	for _, key := range keys {
		var cs *CommandSlice
		ks := slot(key) & uint16(wires-1)
		if cp, ok := ret[ks]; ok {
			cs = cp.cs
		} else {
			cs = get()
			cs.s = append(cs.s, cmd)
			cs.l = 1
			ret[ks] = Completed{cs: cs, cf: cf, ks: ks}
		}
		cs.s = append(cs.s, key)
		cs.l++
	}
	return ret
}
```

**Comment by arielzach** [comment]
> > The capped `concurrency` is likely going to make your batch of userIDs complete after many turns. Is that the same as your observation?
> 
> Yes exactly, The fact that for a `300` batch MGET, 300 sequential separate commands are issued will cause this behavior.
> 
> Apart from your suggested solution. Can't batch MGet Keys be based on pipe number instead of slot?
> 
> If we have access to `multiplex` number in `helper.go`, we can change the mapping from `slot -> CMD` to `pipeNumber -> CMD`. This will solve the problem for sentinel and single clients since `pipeNumber = cmd.Slot() & (len(wire) - 1)`.
> 
> I've tested this scenario and it achieved more than 10X better performance for `MGet` and 3x improvement for `MGetCache`.
> 
> ```go
> func MGetCache(client Client, ctx context.Context, ttl time.Duration, keys []string) (ret map[string]RedisMessage, err error) {
> 	if len(keys) == 0 {
> 		return make(map[string]RedisMessage), nil
> 	}
> 	switch client.(type) {
> 	case *singleClient:
> 		if mux, ok := client.(*singleClient).conn.(*mux); ok {
> 			//return parallelMGet(client, ctx, cmds.MGets(keys), keys)
> 			return parallelMGetCache(client, ctx, ttl, cmds.WireMGets(len(mux.wire), keys), keys)
> 		}
> 	}
> 	return parallelMGetCache(client, ctx, ttl, cmds.MGets(keys), keys)
> }
> ```
> 
> and
> 
> ```go
> func WireMGets(wires int, keys []string) map[uint16]Completed {
> 	return wireSlotMCMDs(wires, "MGET", keys, mtGetTag)
> }
> 
> func wireSlotMCMDs(wires int, cmd string, keys []string, cf uint16) map[uint16]Completed {
> 	ret := make(map[uint16]Completed, 8)
> 	for _, key := range keys {
> 		var cs *CommandSlice
> 		ks := slot(key) & uint16(wires-1)
> 		if cp, ok := ret[ks]; ok {
> 			cs = cp.cs
> 		} else {
> 			cs = get()
> 			cs.s = append(cs.s, cmd)
> 			cs.l = 1
> 			ret[ks] = Completed{cs: cs, cf: cf, ks: ks}
> 		}
> 		cs.s = append(cs.s, key)
> 		cs.l++
> 	}
> 	return ret
> }
> ```
> 
> Benchmark result:
> 
> ```
> BenchmarkClients/rueidis.MGetCache         	   11870	    483803 ns/op	  117839 B/op	     412 allocs/op
> BenchmarkClients/rueidis.MGetCache         	   12794	    571292 ns/op	  116355 B/op	     400 allocs/op
> BenchmarkClients/rueidis.MGetCache         	   12507	    520319 ns/op	  113744 B/op	     379 allocs/op
> BenchmarkClients/rueidis.MGetCache         	   12062	    520157 ns/op	  112699 B/op	     370 allocs/op
> BenchmarkClients/rueidis.MGetCache         	   10000	    506376 ns/op	  111917 B/op	     364 allocs/op
> BenchmarkClients/rueidis.MGetCache         	   11847	    542539 ns/op	  109701 B/op	     345 allocs/op
> BenchmarkClients/rueidis.MGetCache         	   12400	    517694 ns/op	  107896 B/op	     330 allocs/op
> BenchmarkClients/rueidis.MGetCache         	   12243	    497056 ns/op	  106210 B/op	     316 allocs/op
> BenchmarkClients/rueidis.MGetCache         	    9736	    525500 ns/op	  105754 B/op	     312 allocs/op
> BenchmarkClients/rueidis.MGetCache         	   10000	    521483 ns/op	  103981 B/op	     298 allocs/op
> BenchmarkClients/rueidis.MGet              	   10000	    532487 ns/op	  115585 B/op	     299 allocs/op
> BenchmarkClients/rueidis.MGet              	   10000	    545971 ns/op	  115443 B/op	     298 allocs/op
> BenchmarkClients/rueidis.MGet              	   11106	    608166 ns/op	  115215 B/op	     296 allocs/op
> BenchmarkClients/rueidis.MGet              	   10000	    571562 ns/op	  115072 B/op	     295 allocs/op
> BenchmarkClients/rueidis.MGet              	    9771	    557587 ns/op	  114958 B/op	     295 allocs/op
> BenchmarkClients/rueidis.MGet              	   11544	    562008 ns/op	  114690 B/op	     293 allocs/op
> BenchmarkClients/rueidis.MGet              	   10000	    512638 ns/op	  114535 B/op	     292 allocs/op
> BenchmarkClients/rueidis.MGet              	   11497	    558208 ns/op	  114282 B/op	     291 allocs/op
> BenchmarkClients/rueidis.MGet              	   10818	    585721 ns/op	  113999 B/op	     289 allocs/op
> BenchmarkClients/rueidis.MGet              	   10000	    535166 ns/op	  113826 B/op	     288 allocs/op
> ```
> 
> I can provide a PR with this change if that's OK with you.

Hello, 

Currently, we are experiencing the same performance issue when using MGET with Redis in cluster mode. Does this possible solution also apply to this type of architecture?

**Comment by smf8** [comment]
Hello @arielzach, 

Unfortunately, it would be more complicated since the mapping from `slot` to `pipe` is not as simple as in other types of clients. But a change to reduce the size of the mapping (the result of `cmds.Mgets()`) will have a noticeable effect on performance.

**Comment by rueian** [comment]
Hi @smf8, @arielzach,

> If we have access to multiplex number in helper.go, we can change the mapping from slot -> CMD to pipeNumber -> CMD. This will solve the problem for sentinel and single clients since pipeNumber = cmd.Slot() & (len(wire) - 1).

Yes, that's what I proposed. Group CMDs to the underlying pipes, not slots. But as @arielzach pointed out, we had better handle the cluster case as well.

Actually, the same problem exists in almost all the usages of `util.ParallelKeys` and `util.ParallelVals`. Most of them are paralleling by slot now. I think we need to have a function for each type of client implementation that can group CMDs to the pipes, or at least the tuples of [mux, wireindex]

**Comment by arielzach** [comment]
> Hi @smf8, @arielzach,
> 
> > If we have access to multiplex number in helper.go, we can change the mapping from slot -> CMD to pipeNumber -> CMD. This will solve the problem for sentinel and single clients since pipeNumber = cmd.Slot() & (len(wire) - 1).
> 
> Yes, that's what I proposed. Group CMDs to the underlying pipes, not slots. But as @arielzach pointed out, we had better handle the cluster case as well.
> 
> Actually, the same problem exists in almost all the usages of `util.ParallelKeys` and `util.ParallelVals`. Most of them are paralleling by slot now. I think we need to have a function for each type of client implementation that can group CMDs to the pipes, or at least the tuples of [mux, wireindex]. So that we can then pipe them through `DoMulti` and `DoMultiCache`.
> 
> For a short-term solution, setting a larger `runtime.GOMAXPROCS` will help.

Would setting a high value in runtime.GOMAXPROCS make mget perform better in cluster mode? What would be the appropriate value?

**Comment by rueian** [comment]
> Would setting a high value in runtime.GOMAXPROCS make mget perform better in cluster mode? What would be the appropriate value?

From my own experience, twice of your host CPU count is a good starting point.

**Comment by arielzach** [comment]
> > Would setting a high value in runtime.GOMAXPROCS make mget perform better in cluster mode? What would be the appropriate value?
> 
> From my own experience, twice of your host CPU count is a good starting point.

Would it be necessary to modify this portion of code in parallel.go?

```go
func closeThenParallel[V any](ch chan V, fn func(k V)) {
	close(ch)
	concurrency := len(ch)
	if cpus := runtime.GOMAXPROCS(0); concurrency > cpus {
		concurrency = cpus
	}
```

**Comment by rueian** [comment]
@arielzach

No, it won't. You can set it via the `GOMAXPROCS` env.

**Comment by arielzach** [comment]
Beyond increasing GOMAXPROCS, what would be the correct solution to improve the performance of mget?

**Comment by arielzach** [comment]
@rueian 

We ran the tests by setting GOMAXPROCS to twice the number of CPUs, and we obtained the same results.

**Comment by rueian** [comment]
> @rueian
> 
> We ran the tests by setting GOMAXPROCS to twice the number of CPUs, and we obtained the same results.

Hi @arielzach, it sounds to me that the GOMAXPROCS was not set successfully. Did you set CPU limit or quota at the same time?

**Comment by rueian** [comment]
Hi @smf8, @arielzach 

Following https://github.com/redis/rueidis/pull/280, I made a PR https://github.com/redis/rueidis/pull/281 that could speed up `rueidis.MGet` and `rueidis.MGetCache` in all three clients.

Benchmarks are in the link. Hope that the performance is reasonable for you now.

**Comment by smf8** [comment]
Thank you, I'll test it as soon as it's merged and share the result here.

**Comment by rueian** [comment]
> Thank you, I'll test it as soon as it's merged and share the result here.

Thanks @smf8. it's merged. And now we are using separate `GET`s in the `rueidis.MGetCache` helper, but I think we can still make special cases for the single client and the sentinel client to use `MGET`s. Would you like to file a PR for that?

**Comment by smf8** [comment]
Thank you so much. Sure, I'll do it.

**Comment by smf8** [comment]
I've upgraded the client and tested rueidis again. I wanted to share the results here.

![image](https://github.com/redis/rueidis/assets/14906511/32c3ec15-56fe-48b6-b69d-dbf41f757e06)

**Comment by rueian** [comment]
Many thanks @smf8, are these the results of `MGet` or `MGetCache`?

**Comment by smf8** [comment]
Sorry, I forgot to mention. It's the result of `MGetCache`. Somehow, I'm still not satisfied with the results. Despite a significant drop in redis resource metrics which is a result of cache hits, this won't be sensed on the application side.

I plan to perform some CPU profiling to see if anything unusual is causing this. I'll share the result once it's done.

**Comment by rueian** [comment]
Did you expect all cache hit? Maybe you could try increase the size of the client side cache as well.

**Comment by smf8** [comment]
Hi, 
Sorry for the delay. It's not all cache hit but a noticeable portion of **keys** (not `MGet` Queries) are answered by the cache (around 85%). After some digging around. It seems that the CPU consumption difference in clients is caused by `lru.Flight()` which is normal considering that application itself is handling a large portion of keys. 

One thing left for me to test is to setup a custom `cache` struct and use `NewSimpleCacheAdapter()`.

**Comment by smf8** [comment]
> but I think we can still make special cases for the single client and the sentinel client to use `MGET`s

I can think of using normal MGet,MDel, etc for non-cached queries for these clients. Do you have any other special case in mind?

**Comment by rueian** [comment]
> I can think of using normal MGet,MDel, etc for non-cached queries for these clients. Do you have any other special case in mind?

All non-cached helpers have already treated the single client specially. We can let them specially treat the sentinel client as well. And the one we missed is `JsonMGetCache`.

**Comment by rueian** [comment]
Hey @smf8,

> It's not all cache hit but a noticeable portion of keys (not MGet Queries) are answered by the cache (around 85%).

Then I guess your p80 latency got improved?

BTW, I also looked into the CPU profiles, and I found there was an opportunity to improve performance by recycling intermediate allocations used in the `MGetCache`. Here is my initial experiment, https://github.com/redis/rueidis/pull/283, and the result:

Before:
```
Benchmark
Benchmark/MGetCache
Benchmark/MGetCache-10         	   35938	     33182 ns/op	  136428 B/op	      40 allocs/op
PASS
```

After:
```
Benchmark
Benchmark/MGetCache
Benchmark/MGetCache-10         	   52671	     22881 ns/op	   60830 B/op	      28 allocs/op
PASS
```

It shows about 1.4x throughput improvement even though the PR https://github.com/redis/rueidis/pull/283 is just a quick draft. Would you be interested in testing this in your experiment?

**Comment by smf8** [comment]
> Then I guess your p80 latency got improved?

Yes. That's true. for p90 latency we can see the improvements. but in high loads, we see CPU throttles which increased the latency drastically.

Also, Can we improve locking mechanisms for `lru` methods? There was a lot of lock contention in my block profilings. Actually, I don't know if it makes any significant difference, so If its implementation cost is high, we can ignore it.

> Would you be interested in testing this in your experiment?

Sure, I can test it on Saturday.

**Comment by rueian** [comment]
> Also, Can we improve locking mechanisms for `lru` methods? There was a lot of lock contention in my block profilings. Actually, I don't know if it makes any significant difference, so If its implementation cost is high, we can ignore it.

Yes, I am considering this as well. One way to improve it may be just a batch version of Flight. I will give it a try.

**Comment by rueian** [comment]
A batch version of Flight does improve 1.2x throughput.

Before:
```
Benchmark
Benchmark/MGetCache
Benchmark/MGetCache-10         	   50653	     22980 ns/op	   59474 B/op	      18 allocs/op
PASS
```
After:
```
Benchmark
Benchmark/MGetCache
Benchmark/MGetCache-10         	   61290	     19573 ns/op	   59208 B/op	      18 allocs/op
PASS
```

**Comment by rueian** [comment]
Hi @smf8,

v1.0.10 has been released, containing all the optimizations in the draft. Now, for the cache hit case, `MGetCache` can have 35% throughput improvement.

**Comment by smf8** [comment]
Hi @rueian, Thank you for the awesome work. I've drafted the PR (#290) to update helper functions for non-cached methods. Check it out and tell me if anything else should be changed.

**Comment by rueian** [comment]
Thanks. That looks good to me. Many thanks!

**Comment by SoulPancake** [comment]
This is concluded right? @rueian

**Comment by rueian** [comment]
> This is concluded right? @rueian

Hi @SoulPancake,

Almost, but there is still some room for further improvement.

We did recycle some intermediate allocations in https://github.com/redis/rueidis/commit/95e5094771ac079bd14ee07ecfad851e7d66694d, but some allocations in helper.go have not been recycled, for example: https://github.com/redis/rueidis/blob/47c3d7c027ff8b212885c5fa5378bbb687bc36fb/helper.go#L16

Would you like to try recycle them to see if that can improve performance?

**Comment by SoulPancake** [comment]
Yes, I will work on this today @rueian

**Comment by rueian** [comment]
Hi @smf8, v1.0.11 has been released including your patch. Did it work well on your sentinel?

**Comment by smf8** [comment]
Hi @rueian, thank you for the effort. Yes, we sensed the improvement in CPU usage. But I believe the increase in CPU usage in case of large `MGet` queries will be inevitable.

The reduction in the CPU usage of Redis will appear as an increase in the CPU usage of the application.

**Comment by rueian** [comment]
> Yes, I will work on this today @rueian


Hi @SoulPancake, hope you are doing well. Would you be still interested in implementing the optimization?

**Comment by SoulPancake** [comment]
> > Yes, I will work on this today @rueian
> 
> 
> Hi @SoulPancake, hope you are doing well. Would you be still interested in implementing the optimization?
> 
> 

Hey @rueian Sorry for the delay, I have some busy days at school and work didn't get time at all.
I am interested but not sure about my availability, You can proceed with this earlier if you want.
Sorry for not informing

**Comment by rueian** [comment]
Hey @SoulPancake, that's ok. We aren't in a hurry for the optimization. Please stay with your own priority.

**Comment by SoulPancake** [comment]
Hi @rueian Wanted to know the best way to benchmark this with the recycling

**Comment by rueian** [comment]
> Hi @rueian Wanted to know the best way to benchmark this with the recycling

Here is an example https://github.com/redis/rueidis/pull/295

**Comment by rueian** [comment]
> As discussed with @SoulPancake above, there is still room to reduce allocations to these helpers and that may also reduce some CPU usage.
> 

The room for optimization has been addressed by https://github.com/redis/rueidis/pull/333

**Comment by SoulPancake** [comment]
Thanks @rueian 
Sorry I couldn't spend time on it

**Comment by rueian** [comment]
Hi @SoulPancake, it was ok. Don't be sorry on this.
