### ISSUE TITLE
Benchmark using Free Redis Enterprise

### ISSUE THREAD

**Issue by da-tai** [redis/rueidis#289]
When testing with Redis Enterprise, it would seem Go Redis is the best. Is this expected? P.S. to use Redis Enterprise, I had to Disable Caching.

![image](https://github.com/redis/rueidis/assets/137142/2d4fcde4-eca8-47ea-a3c8-71621369ba66)

**Comment by rueian** [comment]
Hi @da-tai,

You probably misinterpreted your screenshot. From your screenshot, rueidis is better in terms of throughput and allocations.
