### ISSUE TITLE
Dump RedisResult response structures to console/log/JSON/etc.

### ISSUE THREAD

**Issue by derekm** [redis/rueidis#292]
`RedisResult` structures can be quite complex and counterintuitive to navigate initially (being nested lists of lists of different sizes).

To support rapid prototyping, there should be a convenient way to dump response structures to a human-readable format for inspection during early development and debugging phases.

**Comment by rueian** [comment]
I agree. One solution would be Implementing [fmt.Stringer()](https://golang.org/pkg/fmt/#Stringer) on the `RedisResult` structure. The implementation would be similar to this:
https://github.com/redis/rueidis/blob/47c3d7c027ff8b212885c5fa5378bbb687bc36fb/message.go#L1027-L1063

**Comment by derekm** [comment]
Thanks for the tip, @rueian! I'll see if I can work something up for my own needs. Hopefully I come back soon with a PR!

**Comment by rueian** [comment]
Thanks @derekm! I am really looking forward to it.

**Comment by rueian** [comment]
Hi @derekm, hope you are doing well. Would you be still interested in implementing this feature?
