### ISSUE TITLE
golang/mock archived

### ISSUE THREAD

**Issue by dlsrb6342** [redis/rueidis#297]
- golang/mock is archived and uber-go/mock is maintained fork instead.
- rueidis/mock is still using golang/mock. Can we change to uber-go/mock?

**Comment by rueian** [comment]
Hi @dlsrb6342,

Sure! Would you like to help to change it?

**Comment by dlsrb6342** [comment]
@rueian 

Yes sure. I'll make a PR soon

**Comment by dlsrb6342** [comment]
@rueian 
any plan for next release?

**Comment by rueian** [comment]
Hi @dlsrb6342,
I usually do release on weekends. Or do you mean you want to contribute something else?

**Comment by dlsrb6342** [comment]
no. I just wanted to use uber-go/mock :) I'll waiting next release.
