### ISSUE TITLE
Go-redis Pool Stats

### ISSUE THREAD

**Issue by da-tai** [redis/rueidis#311]
Does rueidis have Pool Stats similar to Go redis https://pkg.go.dev/github.com/redis/go-redis/v9#Client.PoolStats ?

**Comment by rueian** [comment]
Hi @da-tai,

We don’t have one currently. What kind of metrics you would like to monitor? Do you have some trouble while using rueidis?

**Comment by da-tai** [comment]
Thanks for asking. I've migrated code from go-redis to rueidis. In some cases, I am either getting "error": "context deadline exceeded" or use of closed network connection when using rueidis. I'm not sure why. It also looks like while it's attempting to write to DB before it gets either one of the errors, there is some sort of blocking. I'm using redis labs.

**Comment by rueian** [comment]
It looks like rueidis fails to periodically PING the server or there are other networking issues.

you may try disabling timeout and periodical PING by setting ConnWriteTimeout and Dailer.KeepAlive to negative values to identify the cause.

https://github.com/redis/rueidis/blob/af14e15e4400120766ddd5b7786e7c96c36ffe27/rueidis.go#L288-L294

**Comment by da-tai** [comment]
Hey there. Thanks for this. I figured out the issue (user error). I ran `r.client.DoMulti(ctx, cmds...)` a second time which created the issue above.

Concerning the original question, I normally look at logs and try to keep track of misses, hits, and timeouts.
https://pkg.go.dev/github.com/redis/go-redis/v9@v9.0.5/internal/pool#Stats

I can try looking for a 3rd party app like new relic or datadog for this info.

**Comment by da-tai** [comment]
Is there anyway to get latency per command?

**Comment by rueian** [comment]
Hi @da-tai,

We have https://github.com/redis/rueidis/tree/main/rueidisotel which allows you to collect traces to figure out latencies, including per command or p99, etc.

If rueidisotel doesn't fit your needs, then you can use https://github.com/redis/rueidis/tree/main/rueidishook instead.
