### ISSUE TITLE
Clear builder slice to help GC

### ISSUE THREAD

**Issue by ash2k** [redis/rueidis#312]
https://github.com/redis/rueidis/blob/9e1f9f0047560439ff5ffb3ee0b182092b74dac7/internal/cmds/builder.go#L53-L58

The code above needs to remove references to strings before reslicing the slice so that GC can collect those strings. Otherwise the backing array of the slice still references the strings and GC cannot collect them.

This issue is mentioned here https://github.com/golang/go/wiki/SliceTricks#delete-without-preserving-order.

Go 1.21 will have the `clear()` builtin (see [release notes](https://tip.golang.org/doc/go1.21#language)), so perhaps there can be two versions of code using build tags - for Go 1.21+ using `clear()` and for older versions using a simple loop.

**Comment by rueian** [comment]
Hi @ash2k,

I believe the GC problem you mentioned is not severe given that patterns of commands a program uses are fixed. There are many chances to override strings in the backing array and sync.Pool will also be cleaned by GC after several rounds.

However, I agree that eagerly cleaning the slice up is better to avoid some extreme cases, such as leaving very long strings at the end of slices. The only concern is if the cleanup loop cost too much.

BTW, how to use build tags for having two versions of code simultaneously?

**Comment by ash2k** [comment]
The slice's array is likely in the cpu cache because it has just been used so it should be super cheap to clean it up.

You can have multiple versions by using build tags in separate files. In this case you can have:
- `clear_version.go` that has `//go:build go1.21` tag and uses `clear()`.
- `loop_version.go` that has `//go:build !go1.21` tag and uses `for` loop.

See https://pkg.go.dev/cmd/go#hdr-Build_constraints.

**Comment by rueian** [comment]
Will `//go:build !go1.21` apply to go 1.22?

**Comment by ash2k** [comment]
No, it will not. See the docs:

> a term for each Go major release, through the current version: "go1.1" from Go version 1.1 onward, "go1.12" from Go 1.12, and so on.

Go 1.1 has `go1.1` tag. Go 1.2 has `go1.1` and `go1.2` tags and so on.

**Comment by rueian** [comment]
Sorry that I missed the word "onward". So the `go1.21` flag applies to >= 1.21 and the `!go1.21` applies to < 1.21.

But with these build flags, can we keep the same `go 1.20` version in the go.mod?

**Comment by ash2k** [comment]
Yes, I believe so.
