### ISSUE TITLE
Export cmds.Builder type

### ISSUE THREAD

**Issue by ash2k** [redis/rueidis#314]
I need to write a function that accepts either a `Client` or a `DedicatedClient`. It only needs `B()` and `Do()` methods. I tried to define an interface with just these two methods but it wouldn't compile because `B()` returns `cmds.Builder` type. This type is under `internal/cmds` package and Go compiler doesn't let me use the contents of an `internal` package. I'm getting:

```go
import (
    "github.com/redis/rueidis"
    "github.com/redis/rueidis/internal/cmds"
)

type myClient interface {
	B() cmds.Builder
	Do(context.Context, rueidis.Completed) rueidis.RedisResult
}
```

```
my_source_file.go:13:2: use of internal package github.com/redis/rueidis/internal/cmds not allowed
```

Please consider moving the type somewhere else or creating a type alias in an exported package e.g. the root package.

```go
package rueidis

import (
    "github.com/redis/rueidis/internal/cmds"
)

type Builder = cmds.Builder
```

This is the technique used by e.g. gRPC, see: https://github.com/grpc/grpc-go/blob/20c51a9f425d1f3c4e93eadf25c0464fb794919b/channelz/channelz.go#L36

I think this will not be a breaking change because nobody could have imported the type before the change and hence there are no references to it.

**Comment by ash2k** [comment]
Now I see you already use this technique in `cmds.go`. So it should be a trivial change then.

**Comment by ash2k** [comment]
Hah! For a moment I thought I closed the issue accidentally :) Thanks!

**Comment by rueian** [comment]
Hey @ash2k, I also added a `CoreClient` interface so you don't need to define your own one.

**Comment by ash2k** [comment]
Amazing, thank you!
