### ISSUE TITLE
Supports Redis URL

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#317]
go-redis provides a ParseURL function to prepare required parameters for initialization. We should also have one.

**Comment by 0x-chaitu** [comment]
Hi @rueian I would like to work on this.

**Comment by rueian** [comment]
Thanks @0x-chaitu!

**Comment by gaby** [comment]
👍🏻 for adding this, i'm trying to add support for rueidis to an existing library and the main uses case is using the current Redis ParseURL

**Comment by rueian** [comment]
Hi @0x-chaitu, do you need help on this?

**Comment by vamshiaruru32** [comment]
Hi @rueian I was looking for an alternative for this as well. My usecase is very simple, so I was just using url.Parse to parse the dsn and populate the info. However, I am not sure what's the field for DB? Is it `SelectDB`? The doc comment for it is missing, hence my confusion :)

**Comment by rueian** [comment]
> ParseURL

Hi @vamshiaruru32,

We will be most likely to follow the implementation of go-redis here

https://github.com/redis/go-redis/blob/c3098d5f7eba88330638a8b2b3e23d42cd5c9338/options.go#L227-L277

**Comment by shushenghong** [comment]
suggestion:
1. support cluster like: https://github.com/redis/go-redis/blob/master/osscluster.go#L139
`redis://<user>:<password>@<host>:<port>?addr=<host2>:<port2>&addr=<host3>:<port3>`
2. support more options in dsn like `DisableCache` :)
`?clientcache=0`

thus wo can use config file to init db connection( the init db function maybe inside some private library and cann't be modified by users)

**Comment by rueian** [comment]
Thanks @shushenghong! It is definitely a good idea to support multiple addresses and more options. Would you like to contribute to these features?

To be clear, while currently the `ParseURL` only parses one address, rueidis can still work in cluster mode with that.

**Comment by shushenghong** [comment]
sure, ing
