### ISSUE TITLE
EOF error returned when searching any term on a specific index

### ISSUE THREAD

**Issue by shay-dahan** [redis/rueidis#319]
My Code:
`repo := om.NewJSONRepository("", Event{}, memcachedb.RueidisCLient, om.WithIndexName("jsonidx:EVENTS"))
	total, records, err := repo.Search(ctx, func(search om.FtSearchIndex) rueidis.Completed {
		return search.Query("*").Build()
	})`
	
returned err: "EOF"

Not clear what it means and why the search failed?

**Comment by rueian** [comment]
Hi @shay-dahan,

That typically means it fails to decode incomplete json string the redis responses or the underlying connection unexpectedly ended.

I saw you used a custom index name. Did the index and record were also created by the om.JSONRepository?

**Comment by shay-dahan** [comment]
Hi @rueian I created the index manually via the Redis CLI and it works when I use the Redis CLI for example with the same query.

The result of `memcachedb.RueidisCLient.Do(...)` is this list:
`[]github.com/redis/rueidis.FtSearchDoc len: 9, cap: 9, [{Doc: map[string]string nil, Key: ""},{Doc: map[string]string nil, Key: "error"},{Doc: map[string]string nil, Key: ""},{Doc: map[string]string nil, Key: "total_results"},{Doc: map[string]string nil, Key: ""},{Doc: map[string]string nil, Key: "format"},{Doc: map[string]string nil, Key: "STRING"},{Doc: map[string]string nil, Key: "results"},{Doc: map[string]string nil, Key: ""}]`

Do I need to create my indexes in a particular way for the library to work?
Do I need to add a limit or to narrow down my search?

**Comment by rueian** [comment]
Hi @shay-dahan,

Yes, you need to follow the particular way for the `om` library to work. Here is a valid example:

```go
package main

import (
	"context"
	"fmt"
	"github.com/redis/rueidis"
	"github.com/redis/rueidis/om"
)

type Span struct {
	Key string `redis:",key"`
	Svc string `redis:",svc"`
	Tag string `redis:",tag"`
	Ver int64  `redis:",ver"`
}

func main() {
	client, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:6377"}})
	if err != nil {
		panic(err)
	}
	repo := om.NewJSONRepository("span", Span{}, client)

        // create index
	fmt.Println(repo.CreateIndex(context.Background(), func(schema om.FtCreateSchema) rueidis.Completed {
		return schema.FieldName("$.svc").As("svc").Text().FieldName("$.tag").As("tsg").Tag().Build()
	}))

        // create a record
	span := repo.NewEntity()
	span.Svc = "api"
	span.Tag = "component"
	fmt.Println(repo.Save(context.Background(), span))

        // search records with the om repo
	if _, records, err := repo.Search(context.Background(), func(search om.FtSearchIndex) rueidis.Completed {
		return search.Query("*").Build()
	}); err == nil {
		for _, record := range records {
			fmt.Println(record)
		}
	}

        // search records without the om repo
	fmt.Println(client.Do(context.Background(), client.B().FtSearch().Index("myidx").Query("*").Build()).AsFtSearch())
}
```

and the example will output something like this:

```
<nil>
<nil>
&{01H6RJ7CC984NEEJEAHNM0KKVZ api component 1}
1 [{map[$:{"Key":"01H6RJ36TNXYKG7DFFHPX27PRP","Svc":"api","Tag":"component","Ver":1}] :01H6RJ36TNXYKG7DFFHPX27PRP}] <nil>
```

**Comment by rueian** [comment]
> Hi @rueian I created the index manually via the Redis CLI and it works when I use the Redis CLI for example with the same query.
> 
> The result of `memcachedb.RueidisCLient.Do(...)` is this list: `[]github.com/redis/rueidis.FtSearchDoc len: 9, cap: 9, [{Doc: map[string]string nil, Key: ""},{Doc: map[string]string nil, Key: "error"},{Doc: map[string]string nil, Key: ""},{Doc: map[string]string nil, Key: "total_results"},{Doc: map[string]string nil, Key: ""},{Doc: map[string]string nil, Key: "format"},{Doc: map[string]string nil, Key: "STRING"},{Doc: map[string]string nil, Key: "results"},{Doc: map[string]string nil, Key: ""}]`
> 
> Do I need to create my indexes in a particular way for the library to work? Do I need to add a limit or to narrow down my search?

It looked like your records were somehow broken. For the `om.JSONRepository` to work, each of`Doc["$"]` in your records should be at least a valid JSON string. How did you insert them into Redis?

**Comment by shay-dahan** [comment]
@rueian this is the insertion code:
/
```go
func AppendEvent(ctx context.Context, event Event) error {
	key := BuildProcesAccessedFileKey(ctx, event)
	sessionId := utils.GetSessionId(ctx)
	repo := om.NewJSONRepository(sessionId, Event{}, memcachedb.RueidisCLient)
	exp := repo.NewEntity()
	exp.Key = key
	exp.SeenAt = event.SeenAt
	return repo.Save(ctx, exp)
}

type Event struct {
	Key                     string `json:"key" redis:",key"`
	Ver                     int64  `json:"ver" redis:",ver"`
	SeenAt                  int64  `json:"seen_at,omitempty", redis:",seen_at"`
	SessionId               string `json:"session_id,omitempty", redis:",session_id"`
}
``` 

I still get error EOF.

When I run your code as is, I get a different result:
```
Index already exists
<nil>
0 [{map[] } {map[] error} {map[] } {map[] total_results} {map[] } {map[] format} {map[] STRING} {map[] results} {map[] }] <nil>
``` 

I am using `redis/redis-stack:7.2.0-RC2` docker image as my redis server, and I run it locally.

**Comment by rueian** [comment]
Hi @shay-dahan,

I have reproduced your issue with `redis/redis-stack:7.2.0-RC2` image. There is a new response format introduced 2 month ago: https://github.com/RediSearch/RediSearch/commit/0c5fe146b25ca4a175f9ef1d6e42f6980388818b. I will try to support it in the next release of rueidis.

**Comment by shay-dahan** [comment]
Thanks @rueian ! Looking forward

**Comment by rueian** [comment]
> @rueian it also does not work with new instances of redislabs This is my setup:
> 
> ```
> RediSearch v 2.8.4
> RedisJSON v 2.6.4
> RedisTimeSeries v 1.10.4
> RedisBloomv 2.6.3
> ```
> 
> Do you know what version is supported that I can use now?

RediSearch v2.6 is supported
