### ISSUE TITLE
100% CPU usage within *pipe.Do

### ISSUE THREAD

**Issue by tonyhb** [redis/rueidis#328]
Hi.

We're facing an issue with 100% CPU usage via *pipe.Do calls.  Some background:

- We create many highly concurrent Redis calls
- These API calls can sometimes be for the same commands
- Over time, we see Golang itself start to take 100% CPU when copying stacks to create new goroutines, caused by *pipe.Do.

Here's a flamegraph of a profile:

<img width="1688" alt="Screenshot 2023-08-08 at 11 30 17" src="https://github.com/redis/rueidis/assets/306177/c879a345-c411-4935-9234-494d5200b215">

The trouble is, this takes _hours_ to eventually show in production systems.  Over time, it appears we may be leaking goroutines or triggering some internal issue within Golang that breaks how Rueidis manages its pipeline.

Has anyone encountered this, and do we have architectural notes or a roadmap for the pipeline to solve this?  We're doing a deep dive to see if we can reliably reproduce in a fast manner.  So far no dice.

Edit: We're using Go 1.20.5 on x86.

Also of note, we create goroutines in other other places within this callsite, largely with `errgroup.Go`.  Only `*pipe.Do` causes high CPU usage.

**Comment by tonyhb** [comment]
After spending a little while reading code, it seems as though each Redis command is pipelined in the queue (even if synchronous), which creates a new channel and blocks on the channel for a response.

Still reading Golang internals, but it seems as though this is causing issues with Go's amd_64 stack allocation.  `newstack` is called from `morestack` internally which grows as functions increase the stack size.  Reuidis has a function here that's consistently increasing stack sizes, and hitting some internal pathological issue.

I'm wondering if this is related to the channels we're creating for buffered calls, but not sure.

My next questions are:  why does this happen?  How is stack size increased?  Reproducing this has not worked, so I'm left to theory and internals right now.

**Comment by FZambia** [comment]
@tonyhb hello, are you using per-call Context timeouts when sending commands to Redis? I do not want to say that you should not - just thinking that better understanding how exactly you use Rueidis may help. Probably also share your `ClientOption` setup.

**Comment by rueian** [comment]
Hi @tonyhb,

Thank you for reporting this issue.

> After spending a little while reading code, it seems as though each Redis command is pipelined in the queue (even if synchronous), which creates a new channel and blocks on the channel for a response.

Yes, each command will be queued, but there will be no new channel being created. We reuse those channels.

Since this is related to the stack expansion mechanism of a goroutine, I am afraid that the cause is not directly related to rueidis. Stack expansion happens when a goroutine jumps into a function and finds its current stack size is not enough for doing the real work of the function. Therefore, you will be much easier to observe `runtime.newstack` in flamegraphs if you always invoke `client.Do` from a newly created goroutine. For example:

```go
for {
    go func() {
        client.Do(....)
    }
}
```

Could you share how you invoke `client.Do` for further investigation and improvement?

**Comment by tonyhb** [comment]
@rueian we've managed to internally sample many containers as this issue randomly appeared, and it turns out we're hitting this internal go issue: https://github.com/golang/go/issues/47292.

copying context into *pipe.Do triggers stack resizes due to opentelementry's tracing.  we probably have just over 2kb of stack being copied from the context, which is compounding however this library (and we) manage contexts.

I'm going to close this issue as genuinely it seems like this is a Go implementation issue and doesn't lie with this library.  The only caveat being, if there's a way to manage contexts nicer that would be cool.
