### ISSUE TITLE
How to do TS.ADD or TS.MADD with asterisk for timestamp

### ISSUE THREAD

**Issue by half2me** [redis/rueidis#329]
I can't find a way to use `TS.ADD` or `TS:MADD` without specifying a timestamp. Redis allows you to specify a `*` character instead of an explicit timestamp which will result in Redis setting the timestamp.
Is there a way I can do this?

**Comment by rueian** [comment]
Hi @half2me,

Indeed there is no way to use `*` in the current generated command builder to build a `TS` command.

For now, You can use the `client.B().Arbitrary()` builder as a workaround.

**Comment by rueian** [comment]
Also report to https://github.com/RedisTimeSeries/RedisTimeSeries/issues/1504
