### ISSUE TITLE
protocol bug, message handled out of order

### ISSUE THREAD

**Issue by tuziershi** [redis/rueidis#331]
Hello:)
I use v0.0.92 and meet this error, may i know what would cause it? thanks.
 
/root/go/pkg/mod/github.com/rueian/rueidis@v0.0.92/pipe.go:212 +0x5a
created by github.com/rueian/rueidis.(*pipe).background.func1
/root/go/pkg/mod/github.com/rueian/rueidis@v0.0.92/pipe.go:228 +0x7e
github.com/rueian/rueidis.(*pipe)._background(0xc0030dc240)
/root/go/pkg/mod/github.com/rueian/rueidis@v0.0.92/pipe.go:425 +0x89f
github.com/rueian/rueidis.(*pipe)._backgroundRead(0xc0030dc240)
goroutine 420541 [running]:

**Comment by rueian** [comment]
Hi @tuziershi,

There are bugs in v0.0.92. Please update to the latest version

**Comment by tuziershi** [comment]
Hi @rueian 
OK, thanks

**Comment by rueian** [comment]
Hi @simonprickett,

Did the problem solved?
