### ISSUE TITLE
Using client.close() doesn't return anything

### ISSUE THREAD

**Issue by gaby** [redis/rueidis#334]
Hello,

I'm currently trying to migrate an existing interface from `go-redis` to `rueidis`. One of the requirements of the interface is to return an error for `Close()` but this library doesn't return anything as seen here: https://github.com/redis/rueidis/blob/main/client.go#L137

The `go-redis` close() does return an error as seen here: https://github.com/redis/go-redis/blob/v9.0.5/redis.go#L438

What's the reasoning for `rueidis` to not return anything when calling `Close()`?

**Comment by rueian** [comment]
Hi @gaby,

Because I can’t come up with the usage of that error. I mean, as a user, even if there is an error returned when I close the client, then what can I do?

I would also like to know how others use that error.

**Comment by rueian** [comment]
Me too. But in my own experience, those logs can’t help anything.

**Comment by gaby** [comment]
Fair enough, i'm just going to return `nil`. Thanks!
