### ISSUE TITLE
Massive execution of the CLUSTER SLOTS command

### ISSUE THREAD

**Issue by arielzach** [redis/rueidis#335]
Hello,

We experienced some issues with one of our caches. We observed a spike in ClusterBasedCmds, which resulted in a significant increase in CPU usage. While reviewing the SLOW LOGS, we noticed that the commands correspond to CLUSTER SLOTS. Upon investigating the code, I see that in the event of an error, the "shouldRefreshRetry" method calls "refresh," which is responsible for executing CLUSTER SLOTS. The other places from which it is called are pick*, seemingly when the connection is lost. The cache was functioning correctly, and no nodes were added/removed. Do you have any ideas about what might have caused this massive execution of CLUSTER SLOTS commands?

Thank you.

**Comment by rueian** [comment]
Hi @arielzach, 

> Upon investigating the code, I see that in the event of an error, the "shouldRefreshRetry" method calls "refresh," which is responsible for executing CLUSTER SLOTS

Yes, you are right. `shouldRefreshRetry` is the only place that can launch massive execution of CLUSTER SLOTS commands.

I guess your cluster may have some heartbeat troubles resulting in massive `CLUSTERDOWN` errors at the time you observed then that caused massive execution of CLUSTER SLOTS commands retries from rueidis client.

**Comment by arielzach** [comment]
Hi @rueian,

We didn't see any issues in the cluster. We observed 1.3M rpm of CLUSTER SLOTS. Wouldn't it be better to introduce a delay in the execution of this command? I'd rather have a miss before the cluster goes down on me.

**Comment by rueian** [comment]
Yeah, a delay may help. But that can be very tricky and not everyone likes it.

We have already capped single flight on these `refresh` calls. 1.3M RPM seems to be really abnormal. Was it counted from all your clients and redis servers?  BTW, what version of rueidis you were using?

**Comment by arielzach** [comment]
1.3M RPM is the metric we observed in AWS. In this case, we are using version 1.0.0, and the delay could be configurable; by default, it could be set to 0. Were there any changes in later versions that could have prevented this issue?

**Comment by rueian** [comment]
> Were there any changes in later versions that could have prevented this issue?

@arielzach, Yes, https://github.com/redis/rueidis/pull/250 dramatically reduces unnecessary CLUSTER SLOTS.

I strongly recommended you use the latest version.

**Comment by rueian** [comment]
Hi @arielzach, have you tried the latest version?

**Comment by arielzach** [comment]
Hello, next week we will be conducting the tests.

**Comment by arielzach** [comment]
Hello @rueian,

I'd like to bring up a topic that was shared with me by the team. We've noticed that in the `_refresh` method, nothing is being executed on the context. This is affecting the timeouts since it's being controlled later on. The `_refresh` method in the critical path of a command's execution seems to be adding a time overhead. Am I correct in my understanding?

**Comment by rueian** [comment]
Hi @arielzach,

In the current implementation, the `refresh` is mostly executed on another goroutine. https://github.com/redis/rueidis/blob/aebb626a46265a2c7cdf1c400af7035f0dbb8777/cluster.go#L829

But, I think, yes, it will still add time overhead somehow.

**Comment by arielzach** [comment]
> goroutine

It's true, the shouldRefreshRetry command is executed in a goroutine, but not in the pick. Would that influence the timings there, right?

**Comment by rueian** [comment]
Yes, with the retry loop, it will influence the timings.

To verify that, you can set the `DisableRetry` flag in the `rueidis.ClientOption`

**Comment by rueian** [comment]
No. Writes will never be retried regardless of DisableRetry.

**Comment by arielzach** [comment]
Ok, what is the effect of DisableRetry? For instance, does it affect redirects or traffic when adding a node, or only when there are connection issues?

**Comment by rueian** [comment]
DisableRetry disables the retry loop for read-only commands in the following cases:
1. receives `CLUSTERDOWN` from redis
2. receives `TRYAGAIN` from redis
3. other networking issues

**Comment by rueian** [comment]
While removing nodes, you may experience `CLUSTERDOWN` from redis. While balancing key slots, you may experience `TRYAGAIN` from redis. If none of these is the case, then DisableRetry should not have any effect.

**Comment by arielzach** [comment]
Thank you very much for the info. We conducted tests with version 1.0.11 and noticed a significant decrease in CPU usage. We still need to run tests with version 1.0.16.
