### ISSUE TITLE
Key expiration is ignored by Cache

### ISSUE THREAD

**Issue by gaby** [redis/rueidis#336]
Hello again,

I'm currently building a storage driver for [GoFiber](https://github.com/gofiber/fiber) using `rueidis`. While running the same unit-tests used for `redis` I encountered that the `Cache()` ignores the expiration set during `Set()`

Example Set/Get interface:

```go
// Get value by key
func (s *Storage) Get(key string) ([]byte, error) {
	if len(key) <= 0 {
		return nil, nil
	}
	val, err := s.db.DoCache(context.Background(), s.db.B().Get().Key(key).Cache(), cacheTTL).AsBytes()
	if err == rueidis.Nil {
		return nil, nil
	}
	return val, err
}

// Set key with value
func (s *Storage) Set(key string, val []byte, exp time.Duration) error {
	if len(key) <= 0 || len(val) <= 0 {
		return nil
	}
	return s.db.Do(context.Background(), s.db.B().Set().Key(key).Value(utils.ToString(val)).Build()).Error()
}
```

Example unit-test:

```go
func Test_Rueidis_Set_Expiration(t *testing.T) {
	var (
		key = "john"
		val = []byte("doe")
		exp = 1 * time.Second
	)

	err := testStore.Set(key, val, exp)
	utils.AssertEqual(t, nil, err)

	time.Sleep(1100 * time.Millisecond)
}

func Test_Rueidis_Get_Expired(t *testing.T) {
	key := "john"

	result, err := testStore.Get(key)
	utils.AssertEqual(t, nil, err)
	utils.AssertEqual(t, true, len(result) == 0)
}
```

Is this expected behavior? Am I doing something wrong, or do I need to set something so the Cache will be invalidated once key expires?

Related: https://github.com/gofiber/storage/pull/931

**Comment by rueian** [comment]
Hi @gaby,

It seems like the `exp` parameter of your `Set` function is not used.

**Comment by rueian** [comment]
@gaby,

Most people use `SET key val EX seconds` to set expiration while creating a key.

The corresponding syntax for the command builder is:
```go
client.B().Set().Key("key").Value("val").Ex(time.Second).Build()
```

**Comment by gaby** [comment]
@rueian I was looking at that earlier. I'm not sure why is doing a simple `Set()` with expiration so complicated compared to `go-redis`. I will start looking into making the changes tonight. Thanks for your help!

**Comment by gaby** [comment]
I found the `Ex()` function here: https://github.com/redis/rueidis/blob/main/internal/cmds/gen_string.go#L262C20-L262C20

I'm guessing that having: `int64(0/time.Second), 10)` is causing the error i'm seeing.

**Comment by rueian** [comment]
You probably just need an if-else section to use either:

```go
client.B().Set().Key("key").Value("val").Build()
```

or

```go
client.B().Set().Key("key").Value("val").Ex(time.Second).Build()
```

**Comment by gaby** [comment]
@rueian Thanks, that solved the problem!
