### ISSUE TITLE
Use CLUSTER SHARDS instead of CLUSTER SLOTS.

### ISSUE THREAD

**Issue by arielzach** [redis/rueidis#350]
With the release of Redis 7, the command "CLUSTER SLOTS" will be deprecated, and you should use "CLUSTER SHARDS" instead.

**Comment by Exca-DK** [comment]
Does that mean that everything related to slots should be swapped with shards, or should both coexist?

**Comment by rueian** [comment]
They should both exist because CLUSTER SHARDS only works for redis >= 7

**Comment by arielzach** [comment]
The CLUSTER SLOTS command will be deprecated in future versions; instead, the CLUSTER SHARDS command should be used, which offers performance improvements.
