### ISSUE TITLE
Export RedisResult.err or add create function

### ISSUE THREAD

**Issue by tamayika** [redis/rueidis#352]
Hi, I've started to use rueidis instead of redigo.
I would like to write test code for handling network errors in rueidis, but RedisResult.err is not exported, so I can't mock rueidis.Client properly.

**Comment by rueian** [comment]
Hi @tamayika,

Due to the design of the command builder, it is impossible for users to mock rueidis.Client for testing.

Have you checked [rueidis mock](https://github.com/redis/rueidis/tree/main/mock#rueidis-mock)? That should help you test code for handling network errors.

**Comment by tamayika** [comment]
Thanks for the quick reply!

I didn't know the mock library existing.
I will try it tomorrow.

**Comment by fabiomargarido** [comment]
Hey, I was about to open an issue requesting an exported func to create a new RedisResult, but for a different reason.

In my case, I'm implementing a hook to be used with rueidishook, and in my implementation of `Do`, for instance, I want to return an arbitrary error, other than the one potentially returned by the call to `client.Do`, but haven't found a way to do so. Is this currently possible?

**Comment by fabiomargarido** [comment]
Thanks for the quick reply and for the suggestion.

I'll use that for now, but it feels kinda dirty to import the mock library just for this 😄 
Is there a technical reason why something like `NewRedisResult(val, err)` cannot be in the library?

**Comment by rueian** [comment]
Hi @fabiomargarido,

Sorry for pointing you to the mock library. I just found that we have `rueidishook.NewErrorResult`
https://github.com/redis/rueidis/blob/d2565be74c82cdde22a85a6ef94cf6d93cf329e8/rueidishook/hook.go#L166-L169

So, you don't have to import the mock library.

**Comment by fabiomargarido** [comment]
Oh, that's a lot nicer, and sorry for not having found that before asking 😳
