### ISSUE TITLE
Export cluster slot function

### ISSUE THREAD

**Issue by tamayika** [redis/rueidis#354]
ClusterClient does not support multi keys command across different slots.
(https://github.com/redis/rueidis/blob/main/internal/cmds/cmds.go#L347C17-L347C17)

If [slot](https://github.com/redis/rueidis/blob/main/internal/cmds/slot.go#L5) function is exported, I can split keys before building commands.

**Comment by rueian** [comment]
Hi @tamayika,

Sure, we can export the slot function.

Besides exporting it, we also have rueidis.MGET helpers. Would it fit your needs?

**Comment by tamayika** [comment]
No, I want to implement multiple keys DEL.
I don't know DEL helper is better.

**Comment by rueian** [comment]
We also have a MDel helper. You can try that.

**Comment by tamayika** [comment]
Sorry, I was reading your old package(https://pkg.go.dev/github.com/rueian/rueidis).
Currently [MDel](https://pkg.go.dev/github.com/redis/rueidis#MDel) exists.
