### ISSUE TITLE
RedisStack RedisJson设计大key多节点耗性能吗？

### ISSUE THREAD

**Issue by AsukaLay** [redis/rueidis#363]
最近用上了RedisStack 的Json模块

想问一下 一个key 多个json节点和 多个key一个json哪种方案好？

一个key管理一个过期时间但是对应的json数据很大 多个key会有多key过期时间维护

**Comment by rueian** [comment]
多個 key 比較好
巨大的 key 容易影響穩定性

**Comment by AsukaLay** [comment]
谢谢
