### ISSUE TITLE
Memory leak when commands are failing

### ISSUE THREAD

**Issue by creker** [redis/rueidis#364]
**rueidis v1.0.17
Tested on Go 1.21.1 and Go 1.20.8**

Looks like rueidis leaks memory when pipelining commands that later fail. For example, due to context timeout. I suspect they're not getting recycled properly and retain data inside them. I was able to write an example that consistently reproduces the behaviour.

First, let's start with this example that works:
```Go
package main

import (
	"context"
	"fmt"
	"net/http"
	_ "net/http/pprof"
	"time"

	"github.com/redis/rueidis"
)

func work(cl rueidis.Client) {
	for {
		buf := make([]byte, 10000000)

		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Millisecond)

		fmt.Println(cl.Do(ctx, cl.B().Set().Key("test").Value(rueidis.BinaryString(buf)).Build()).Error())

		cancel()

		time.Sleep(time.Second)
	}
}

func main() {
	go func() {
		http.ListenAndServe(":8081", nil)
	}()

	cl, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{"localhost:6379"},
	})
	if err != nil {
		panic(err)
	}

	work(cl)
}

```

This code works and I wasn't able to observe any leaks. It's important that it prints "context deadline exceeded". Without that everything works as expected.

Now, let's make a couple of changes to force the client to pipeline commands. First, we can launch another goroutine in parallel like this:
```Go
go work(cl)
work(cl)
```

Unfortunately, it takes some time. Sometimes 30 seconds, sometimes a couple of minutes. But eventually memory will start ballooning. If we look at the heap profile, it will show that all the allocated memory is in this line:
```Go
buf := make([]byte, 10000000)
```

There's another way to trigger that behaviour. We don't even need to run multiple gorouines. Just enabling `AlwaysPipelining` option consistently and immediately reproduces the memory leak.

**Comment by rueian** [comment]
Hi @creker,

Pipelining does use a certain amount of memory, but it will not balloon memory usage indefinitely.

You can control that certain amount of memory by changing the `RingScaleEachConn` and the `PipelineMultiplex` options.

For example, the following setting will keep occupying about 1.3GB of memory:

```go
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/redis/rueidis"
)

func work(cl rueidis.Client) {
	for {
		buf := make([]byte, 10000000)
		ctx, cancel := context.WithTimeout(context.Background(), time.Millisecond)
		fmt.Println(cl.Do(ctx, cl.B().Set().Key("test").Value(rueidis.BinaryString(buf)).Build()).Error())
		cancel()
	}
}

func main() {
	cl, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress:       []string{"localhost:6379"},
		AlwaysPipelining:  true,
		PipelineMultiplex: -1,
		RingScaleEachConn: 6,
	})
	if err != nil {
		panic(err)
	}
	go work(cl)
	work(cl)
}

```

**Comment by creker** [comment]
@rueian of course, pipelining uses some memory but I wouldn't expect it to depend so much on the size of the commands. All the commands are failing almost immediately. There's only 2 goroutines and minimal amount of inflight requests but rueidis still holds to the command contents. WIth your example it does stop at 1.3GB but I still think this is a problematic behaviour. All that memory is still `buf := make([]byte, 10000000)`, so the initial problem is still there.

**Comment by creker** [comment]
Yeah, bad wording on my part. I can understand the problem. Thank you. At least now I know which knobs to turn in case the problem comes back again. I will close the issue.
