### ISSUE TITLE
Bitfield support missing Get

### ISSUE THREAD

**Issue by cjo2** [redis/rueidis#369]
Hi!

I was trying to build a Redis command like
```
BITFIELD mykey GET u32 0
```

Unfortunately, it looks like the `BitfieldOperationGet` type does not actually have a `Build()` method. Is there another way I should be using the command builder to get the above result?

Ideally, it should look like this:
```
client.B().Bitfield().Key("mykey").Get("u32",0).Build()
```

But so far, it looks like the only other way is by using something like `Incrby()` after my `Get()` to call `Build()`:
```
client.B().Bitfield().Key("mykey").Get("u32", 0).Incrby("u32", 0, 0).Build()
```

**Comment by rueian** [comment]
Hi @cjo2,

I will fix this in the next release. You can use BITFIELD_RO instead now.

**Comment by cjo2** [comment]
Thanks a ton, @rueian!
