### ISSUE TITLE
Rueidislock sometimes goes into infinite loop

### ISSUE THREAD

**Issue by creker** [redis/rueidis#372]
rueidis v1.0.18
Keydb cluster 6.2.2

I use rueidislock to coordinate multiple instances of my application. A couple of times I observed an issue where CPU goes to 100% and rate of commands sent to redis goes through the roof. Looking at cpu profile, it seems like the problem is infinite loop in this part of the code
```Go
ROUTINE ======================== github.com/redis/rueidis/rueidislock.(*locker).try.func1 in github.com/redis/rueidis@v1.0.18/rueidislock/lock.go
      20ms      5.58s (flat, cum) 19.77% of Total
         .          .    268:	monitoring := func(err error, key string, deadline time.Time, csc chan struct{}) {
         .          .    269:		if err == nil {
         .          .    270:			for timer := time.NewTimer(m.interval); err == nil; {
      10ms      130ms    271:				select {
         .          .    272:				case <-ctx.Done():
         .          .    273:					err = ctx.Err()
         .          .    274:				case <-timer.C:
         .          .    275:					deadline = deadline.Add(m.interval)
         .          .    276:					if err = m.script(ctx, extend, key, val, deadline); err == nil {
         .          .    277:						timer.Reset(m.interval)
         .          .    278:						if !m.noloop {
         .          .    279:							<-csc
         .          .    280:						}
         .          .    281:					}
         .          .    282:				case <-csc:
      10ms      5.43s    283:					if err = m.script(ctx, extend, key, val, deadline); err == nil {
         .          .    284:						if !m.noloop {
         .       20ms    285:							<-csc
         .          .    286:						}
         .          .    287:					}
         .          .    288:				}
         .          .    289:			}
         .          .    290:		}
```

Metrics show the same thing. Redis is being bombarded with evalsha, get and pexpireat commands, which exactly matches "extend" lua script. 

The affected instance itself worked as expected. It even held the lock in question and did all the operations as expected.

Unfortunately, I cannot reproduce this issue. It happens very rarely and the only thing that helps is to restart misbehaving instance. Reporting this in hopes that maybe there's some obvious error in the implementation.

**Comment by rueian** [comment]
Hi @creker,

I have identified that this line https://github.com/redis/rueidis/blob/2f2f4da3b9a41c23f922ce5551a90088243393da/rueidislock/lock.go#L234 will cause the monitoring loop to go crazy.

This will happen when a redis server or a keydb server proactively sends a **invalid all cache** message to client.

I will find a solution for this in the next release.
