### ISSUE TITLE
Avoid using QUIT

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#377]
The `QUIT`, as [redis documentation](https://redis.io/commands/quit/) mentioned, is not only deprecated but also hurts server performance actually. Clients should not use it anymore.

However, rueidis currently queues a `QUIT` command here in `Close()` to wait for other pending commands to be completed:
https://github.com/redis/rueidis/blob/2f2f4da3b9a41c23f922ce5551a90088243393da/pipe.go#L320

I think for this purpose, we may use a `PING` to replace `QUIT`.

**Comment by unknowntpo** [comment]
I think I can take this issue, but I may need some help since I'm not familiar with the codebase.
