### ISSUE TITLE
Blocking commands should ignore ClientOption.MaxFlushDelay

### ISSUE THREAD

**Issue by tamayika** [redis/rueidis#379]
Blocking commands are executed in dedicated client which is aquired from pool.
So, there is no sense to wait other commands to be written.

**Comment by rueian** [comment]
Hi @tamayika, good catch. We can add a check if the last command is a blocking one here
https://github.com/redis/rueidis/blob/cb6a8f3146fcc81867e6b2dc205a747871eba13e/pipe.go#L412-L414

would you like to open a PR for this?

**Comment by tamayika** [comment]
I don't know well about pipe's fields usage, please implement this.
