### ISSUE TITLE
Align rueidiscompat with go-redis

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#380]
Although the command builder of rueidis already supports all commands of redis, including commands of RediTimeseries, RedisJSON, RedisBloom, and RediSearch, the `rueidiscompat` doesn't support those modules.

go-redis recently added support for them via the following interfaces:

- [x] GearsCmdable
- [x] ProbabilisticCmdable
- [x] TimeseriesCmdable

We should also implement them in the `rueidiscompat`.

**Comment by unknowntpo** [comment]
I can help.

**Comment by unknowntpo** [comment]
## Survey:

GearsCmdable
we need to implement this interface.
```
https://github.com/redis/go-redis/blob/f994ff1cd96299a5c8029ae3403af7b17ef06e8a/gears_commands.go#L9-L19
```

**Comment by rueian** [comment]
All these Cmdable interfaces have already been added by unknowntpo. Thank you for your great work! @unknowntpo
