### ISSUE TITLE
HSet() - HGet() - HGetAll() - Support pointer Scan/Dereference

### ISSUE THREAD

**Issue by numberinho** [redis/rueidis#385]
Hello and thank you for providing such a nice library with awesome Redis features!

Currently I try to implement a Redis Cache to our new application, where I need to store structs that include pointers. Unfortunately I have to use pointers, because the structs are being populated from MySQL nullable fields, and I would like to keep the information about a field being NULL. All pointers point to "simple data types" such as string, time and time.Time.

Can you give me any hints on how I can implement the feature to store structs in Redis H-Family()? 

The following code may explain my problem:
```
type WithPointer struct {
	Str    string  `redis:"str"`
	StrPtr *string `redis:"strPtr"`
	Int    int     `redis:"Int"`
	IntPtr *int    `redis:"IntPtr"`
}

// Here I'm trying to set the struct. It writes the pointer address to the redis server
func TestRueSet(t *testing.T) {
	client, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"localhost:6386"}})
	if err != nil {
		panic(err)
	}
	defer client.Close()
	compat := rueidiscompat.NewAdapter(client)

	s := "a"
	i := 1
	withPointer := WithPointer{s, &s, i, &i}

	ctx := context.Background()
	err = compat.HSet(ctx, "test:1", withPointer).Err()
	if err != nil {
		t.Errorf("%s", err.Error())
	}
}
//1) "str"
//2) "a"
//3) "strPtr"
//4) "0x14000022070"
//5) "Int"
//6) "1"
//7) "IntPtr"
//8) "0x14000212150"

// Here I'm trying to fetch back the struct.
func TestRueGet(t *testing.T) {
	client, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"localhost:6386"}})
	if err != nil {
		panic(err)
	}
	defer client.Close()
	compat := rueidiscompat.NewAdapter(client)

	var withPointer WithPointer

	ctx := context.Background()
	err = compat.HGetAll(ctx, "test:1").Scan(&withPointer)
	if err != nil {
		t.Errorf("%s", err.Error())
	}
	fmt.Println(withPointer)
}
// Returns: cannot scan redis.result 0x14000022090 into struct field WithPointer.StrPtr of type *string, error-redis.Scan(unsupported string)
```

Somehow, I need to implement for HSet:
(1) If pointer field not null,
(2) Dereference pointer field
(3) Store in cache

And for HGetAll() and HGet()
(1) If field exists in cache
(2) Decode

Do you have any suggestions? Thank you a lot!

**Comment by rueian** [comment]
Hi @numberinho,

That is a reasonable use case, but unfortunately it doesn’t work in the current rueidis. We would like to have the ability to encode and decode pointers of primitive types into redis hash set in the future.

With the current rueidis, you can consider using JSON.SET or just SET to store your structs as json strings.

**Comment by numberinho** [comment]
Hey rueian,

thank you for your kind answer!

My solution for now is to implement the MarshalBinary and UnmarshalText methods on a struct, that embeds a pointer to a primitive. Both methods get called by the combat adapter. 

```
type StringPtr struct{ *string }

func (s StringPtr) MarshalBinary() ([]byte, error) {
	return msgpack.Marshal(s.string)
}

func (s *StringPtr) UnmarshalText(data []byte) error {
	return msgpack.Unmarshal(data, &s.string)
}
```

**Comment by numberinho** [comment]
Can you give me a starting point? I would like to implement a solution in my project and will keep you up to date (if you want!)

**Comment by rueian** [comment]
> Can you give me a starting point?

Sure! Thanks! I saw you already filed a PR https://github.com/redis/rueidis/pull/388.

> Problem: Obviously, if there is a hash with a field, even though the value of the field is empty "", the pointers always point to a valid value, they are never Nil, which I don't know if it can be solved.

Well, if there is a hash field storing an empty string, I think we have no option but to make the corresponding struct field point to an empty string, because, as you said, an empty string is also a valid value.

**Comment by rueian** [comment]
Hi @numberinho, thank you for your PR https://github.com/redis/rueidis/pull/388. Please feel free to let me know if you have other issues with rueidis.

**Comment by numberinho** [comment]
Hi @rueian, thank you for your advices and accepting the PR!

I indeed have another issue that I would like to ask you about. Should I create a new Issue for that?

**Comment by rueian** [comment]
> Hi @rueian, thank you for your advices and accepting the PR!
> 
> I indeed have another issue that I would like to ask you about. Should I create a new Issue for that?

Sure!
