### ISSUE TITLE
Question: Score on KNN Search

### ISSUE THREAD

**Issue by joaolcorreia** [redis/rueidis#386]
Hi! Amazing module for go. I was able to get my KNN search working but I was wondering if any of these 2 things are possible:

- Get the score for each of the results
- Sort by score so we get the best results first

`
cmd := client.B().FtSearch().Index("idx:iss").Query("*=>[KNN 5 @vector $V as score]").
 Params().Nargs(2).NameValue().NameValue("V", rueidis.VectorString32(embeddings)).Dialect(2).Build()
n, results, err := client.Do(ctx, cmd).AsFtSearch()	
`

If not is this the case where you should build an arbitrary command?

Thank you!

**Comment by rueian** [comment]
> Hi! Amazing module for go. I was able to get my KNN search working but I was wondering if any of these 2 things are possible:
> 
> * Get the score for each of the results
> * Sort by score so we get the best results first
> 
> `cmd := client.B().FtSearch().Index("idx:iss").Query("*=>[KNN 5 @vector $V as score]"). Params().Nargs(2).NameValue().NameValue("V", rueidis.VectorString32(embeddings)).Dialect(2).Build() n, results, err := client.Do(ctx, cmd).AsFtSearch() `
> 
> If not is this the case where you should build an arbitrary command?
> 
> Thank you!

Hi @joaolcorreia,

According to the document https://redis.io/docs/interact/search-and-query/advanced-concepts/vectors/#vector-search-examples, you should be able to access the __vec_score. Is that missing from your results?

**Comment by joaolcorreia** [comment]
Thanks @rueian I was able to get it! My other question was the sorting, how can I make sorting by score with the best score  (closer, lower) first?

**Comment by joaolcorreia** [comment]
Got it @rueian ! Thank you!!!
