### ISSUE TITLE
How can I add my Logger to the Client?

### ISSUE THREAD

**Issue by Eugene-Usachev** [redis/rueidis#389]
Rueidis under the hood sends ready requests to Redis. They are a string. Now I can log operations only by writing the log separately from the request. It would be nice if I could pass my structure to the Client, which implements some kind of Logger interface, so that rueidis.Client can log requests.
Correct me if such functionality already exists.

**Comment by rueian** [comment]
Hi @Eugene-Usachev,

You could use the https://github.com/redis/rueidis/tree/main/rueidishook

**Comment by Eugene-Usachev** [comment]
I left the old solution. I would like the library to allow me to throw a logger, but I'm ready to close the problem if you don't have the opportunity to implement it.
