### ISSUE TITLE
Get returns Rueidis.nil even when the key exists

### ISSUE THREAD

**Issue by rokatyal** [redis/rueidis#393]
Hi, I have been trying to move from go-redis to rueidis, we have a loop which checks for keys that donot exist and based on that tries to delete some related keys. I have seen some instances of Get returning a err and that err is rueidis.nil.  Which I am assuming means that the key does not exist. Am i interpreting it wrong ? 

Are there any recommendations, could rueidis be interpreting a different error as nil ? 

We are using memory db redis cluster, we do have lot of long running concurrent connections and I am using the compat layer object

**Comment by rueian** [comment]
Hi @rokatyal,

What operation did you use when you got unexpected rueidis.Nil errors?

**Comment by rokatyal** [comment]
@rueian we have a go routine checking for some certain keys. And we use the compat layer for now. 

```
Compat.Get(ctx, key).Bytes()
```
this is this doesnot behave incorrectly all the time, but sometimes.

**Comment by rueian** [comment]
Hi @rokatyal,

There seems to be no way for rueidis to interpret a different error as nil. I may need more details to help you.

What rueidis version you are using?
What Redis version you are using? Are you using RESP3 or RESP2?
What make you feel that those rueidis.Nils unexpected?
How often or how long does your loop take in time to spot an unexpected Nil?

I have been testing 100M keys on my local cluster with the following program and without errors for a while.

```go
package main

import (
	"context"
	"fmt"
	"strconv"
	"sync/atomic"
	"time"

	"github.com/redis/rueidis"
	"github.com/redis/rueidis/rueidiscompat"
)

func main() {
	c, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:7001"}})
	if err != nil {
		panic(err)
	}
	cc := rueidiscompat.NewAdapter(c)

	nc := 4
	ch := make(chan string, nc*2)
	iw := uint64(0)
	ir := uint64(0)
	for i := 0; i < nc; i++ {
		go func() {
			for {
				k := strconv.FormatUint(atomic.AddUint64(&iw, 1)%100000000, 10)
				if err := cc.Set(context.Background(), k, k, 0).Err(); err != nil {
					panic(err)
				}
				ch <- k
			}
		}()
		go func() {
			for {
				k := <-ch
				if v, err := cc.Get(context.Background(), k).Result(); err != nil || v != k {
					panic(err)
				}
				iw, _ := strconv.ParseUint(k, 10, 64)
				atomic.StoreUint64(&ir, iw)
			}
		}()
	}
	for {
		time.Sleep(5 * time.Second)
		fmt.Println(atomic.LoadUint64(&iw), atomic.LoadUint64(&ir))
	}
}
```

**Comment by rokatyal** [comment]
What rueidis version you are using? v1.0.19-go1.18, Go Version- 1.19

What Redis version you are using? Are you using RESP3 or RESP2?  Redis 7 , 

RESP3 I guess , checking on that

What make you feel that those rueidis.Nils unexpected? Because i can see the key its checking exists before and also during the check. 
 
How often or how long does your loop take in time to spot an unexpected Nil? I will get back on the time taken to report the unexpected nil


I think my main concern was that .Set also returns redis.nil but that could be attributed to the client or just something unexpected happening and we can retry. But Get returning a redis.nil breaks certain assumptions. And i was wondering if that could be something thats happening for Get too, because of contention or too mainly redis connections open 

 Thanks for the prompt replies.  I will try to add more information as i get it.

**Comment by rueian** [comment]
Hi @rokatyal,

> .Set also returns redis.nil

Oh, this might be weird. A `SET` request should only result in a nil when combining `NX`, `XX`, or `GET` options. Did you use those options with `SET`?

**Comment by rokatyal** [comment]
go-redis usually provides these stats as part of the pool struct, not sure we have something similar for rueidis. 

```
// Stats contains pool state information and accumulated stats.
type Stats struct {
	Hits     uint32 // number of times free connection was found in the pool
	Misses   uint32 // number of times free connection was NOT found in the pool
	Timeouts uint32 // number of times a wait timeout occurred

	TotalConns uint32 // number of total connections in the pool
	IdleConns  uint32 // number of idle connections in the pool
	StaleConns uint32 // number of stale connections removed from the pool
}

```

Not sure we have something similar for rueidis ? May be this https://github.com/redis/rueidis/blob/main/rueidisotel is something i need to look into, this seems to provide cache hit and miss, not total connections. 


For the set returning nil 

https://github.com/redis/rueidis#cas-pattern i follow this but with a single key. 
then loop through redisresults and check if any of them are an error and I see redis.nil here "Error\":\"redis nil message\"}
		
Just to give an idea on total connections we do around 3k total connections and more than 1 G total redis hits with go-redis.

**Comment by rokatyal** [comment]
Also i set a ttl when i am setting a value using .ExSeconds(int64(ttl().Seconds())).Build()

**Comment by rueian** [comment]
Hi @rokatyal,

Currently, there is no way to get connection counts from rueidis. If you are using the `client.Dedicated` then the maximum count to each node is determined by the `BlockingPoolSize` option, which the default is 1000.

The https://github.com/redis/rueidis#cas-pattern is much more complex and has many things to be concerned with. For example, a Nil response from the `EXEC` means the transaction was aborted.

Could you provide your code snippets showing how you do the CAS within the `Dedicated` block?

**Comment by rokatyal** [comment]
@rueian I think the reason for receiving returning a nil, because of transaction aborted makes sense. I think its the Get returning nil thats my main concern. For now, i retry the Get Request to alleviate the issue.

**Comment by rokatyal** [comment]
So i think we are confusing two different things, the get call , i didnot pass any TTL.

**Comment by rueian** [comment]
> So i think we are confusing two different things, the get call , i didnot pass any TTL.

I understand. I mean could it be the TTL you specified with SET had been expired, so when you GET, you got nil.

**Comment by rueian** [comment]
BTW, how do you use the `Dedicated` with the rueidiscompat? and do you use redis cluster? do all your nodes respond the same `cluster slots` response?

**Comment by rokatyal** [comment]
@rueian oh hmm , did not think about that, thats a good point about the SET, i doubt it, because the ttl is in days, but i will check that. 
So for dedicated I just used the rueidis client. Yes we use redis cluster, aws memory db, so as far as we know memory db gives us one endpoint for cluster and it manages the nodes underneath it. 

Also we recently deployed in prod with rueidis changes and reverting it, because we are seeing very high cpu utilization when we use rueidi the current rueidis set up, I have caching disabled for now, And maxflush delay set to 100microsecond. Next i am going to try out decreasing the ring buffer size. may be set to 9 for now and deploy the latest 1.20-1.19 buuild

**Comment by rueian** [comment]
Reducing RingScaleEachConn to 8 or 9 will save your client-side memory usage but the CPU utilization would be probably the same.

However, you seem to be heavily dependent on the `Dedicated` function, then reducing the `BlockingPoolSize` to 10 or so will reduce both your client-side CPU and memory usage.

**Comment by rueian** [comment]
Hi @rokatyal,

Is there any update from your last try?

**Comment by rueian** [comment]
Hi @rokatyal,

Please feel free to reopen this issue if you need to.
