### ISSUE TITLE
Is it possible to support setting a unified prefix for keys? 

### ISSUE THREAD

**Issue by OneSeven** [redis/rueidis#396]
As title

**Comment by rueian** [comment]
Hi @OneSeven,

Please checkout https://github.com/redis/rueidis/tree/main/rueidishook

**Comment by rueian** [comment]
Hi @OneSeven, you could enforce your prefix by altering  the cmd passed in. With cmd.Commands(), you can access to the underlying slice of commands.

**Comment by rueian** [comment]
Hi @OneSeven,

Have you figure out how to add prefix to your commands?

**Comment by tinoquang** [comment]
Hi @OneSeven, can you share your approach? I'm facing the same issue. Even if I can access the slice of commands, I still don't know the index of the `key`. Some commands it's the 2nd value, others it's 3rd value

**Comment by pdax-maiquang** [comment]
> > Hi @OneSeven, can you share your approach? I'm facing the same issue. Even when I can access the slice of commands, I still don't know the index of the `key`. Some commands it's the 2nd value, others it's 3rd value
> 
> ```go
> func (h *Hook) Do(client rueidis.Client, ctx context.Context, cmd rueidis.Completed) (resp rueidis.RedisResult) {
> 	// do whatever you want before client.Do
> 	cmd.Commands()[1] = "prefix" + cmd.Commands()[1]
> 	resp = client.Do(ctx, cmd)
> 	// do whatever you want after client.Do
> 	return
> }
> ```

Okay, seems like you're assuming the 2nd value is the key. I'm struggling with commands like `MGet` which I can provide multiple keys
