### ISSUE TITLE
[Feature Request] Randomly pick one of replicas when `ReplicaOnly` is true

### ISSUE THREAD

**Issue by proost** [redis/rueidis#397]
If i'm right, when `ReplicaOnly` option is true, use only one replica for a slot.
```
	slots := [16384]conn{}
	for master, g := range groups {
		addr := master
		if c.opt.ReplicaOnly && len(g.nodes) > 1 {
			addr = g.nodes[1+rand.Intn(len(g.nodes)-1)]
		}
		cc := conns[addr]
		for _, slot := range g.slots {
			for i := slot[0]; i <= slot[1]; i++ {
				slots[i] = cc
			}
		}
	}

	c.mu.Lock()
	c.slots = slots
```

If multiple replicas are exist, then it is waste of resource. How about new option like `AnyReplicas` to randomly select one of replica when `Do` or `DoMutli` are called?

**Comment by rueian** [comment]
Hi @proost,

You are right. The code snippet you mentioned only assigns a random replica to a slot range. 

How about distributing the slot range evenly to replicas? I think there is no need to introduce a new option for this change.

**Comment by proost** [comment]
@rueian 

You mean below lines?
```
		cc := conns[addr]
		for _, slot := range g.slots {
			for i := slot[0]; i <= slot[1]; i++ {
				slots[i] = cc
			}
		}
```
if randomly pick one of node per slot, it can be distributed more evenly without introduciong new option. that's nice. can i contribute this one?

**Comment by rueian** [comment]
Sure! Contributions are always welcome.
