### ISSUE TITLE
Potential memory leak in lru?

### ISSUE THREAD

**Issue by NeoHuang** [redis/rueidis#403]
**rueidis version 1.0.18-go1.18**

**go version 1.18**

I've noticed something that I can't explain yet. we are running an application in k8s with multiple pods. traffic is relatively evenly distributed. some pods have high memory usage while others seems fine. after profiling and notice that the difference is mainly in `doretryCache`

**flame graph of high memory usage pod**
<img width="1410" alt="image" src="https://github.com/redis/rueidis/assets/3006506/4d950c0b-2889-4550-8d4c-22059de633d6">

**flame graph of low memory usage pod**
<img width="1406" alt="image" src="https://github.com/redis/rueidis/assets/3006506/b679dd99-6274-4724-9809-690e5e30b349">

could there be some potential memory leak in some scenarios?

**Comment by rueian** [comment]
Hi @NeoHuang, do you ever see the memory usage of those pods shrink down?

**Comment by NeoHuang** [comment]
nope. Looks like it only keeps growing

**Comment by rueian** [comment]
Hi @NeoHuang,

In order to better reproduce your condition, please provide the following details:

1. How many nodes does your cluster have?
2. How many commands do you put into one DoMultiCache? And what TTLs do you set for them?
3. How large do those command responses generally take?
4. How long does a pod take to grow to over 900MB memory usage?
5. Will reducing the `CacheSizeEachConn` option relieve your memory usage?

**Comment by NeoHuang** [comment]
Hi Rueian,

1. we have 3 shards, 3 nodes for each shard
2. for each DoMultiCache we put less than 10 HGETALL commands and each HGETALL returns normally less than < 5 records
3. each command takes less than 5ms
4. it took about 12hours for some pod to grow to over 900MB. while other pods were stable at 30MB
5. I have to test that and get back to you

**Comment by rueian** [comment]
Hi @NeoHuang,

I have run the following program which simulates your description over a week. Though it uses much more memory than expected, its use of memory remains under 600MB stably.

```go
package main

import (
	"context"
	"log"
	"math/rand"
	"net/http"
	"strconv"
	"time"

	"github.com/redis/rueidis"
	_ "net/http/pprof"
)

func main() {
	go func() {
		log.Println(http.ListenAndServe("localhost:6060", nil))
	}()

	c, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress:       []string{"127.0.0.1:7001", "127.0.0.1:7002", "127.0.0.1:7003"},
		CacheSizeEachConn: 64 * (1 << 20),
	})
	if err != nil {
		panic(err)
	}
	defer c.Close()

	ch := make(chan []string)
	go func() {
		cmds := make([]rueidis.Completed, 10)
		for {
			gets := make([]string, 10)
			for j := 0; j < 10; j++ {
				gets[j] = strconv.FormatUint(uint64(rand.Uint32()), 10)
				hsets := c.B().Hset().Key(gets[j]).FieldValue()
				for i := 0; i < 5; i++ {
					hsets = hsets.FieldValue(strconv.FormatUint(uint64(rand.Uint32()), 10), gets[j])
				}
				cmds[j] = hsets.Build()
			}
			for _, resp := range c.DoMulti(context.Background(), cmds...) {
				if err := resp.Error(); err != nil {
					panic(err)
				}
			}
			ch <- gets
		}
	}()

	for ids := range ch {
		for j := 0; j < 10; j++ {
			go func(ids []string) {
				cmds := make([]rueidis.CacheableTTL, 10)
				for i, id := range ids {
					cmds[i] = rueidis.CT(c.B().Hgetall().Key(id).Cache(), 15*time.Minute)
				}
				ctx, cancel := context.WithTimeout(context.Background(), time.Second)
				defer cancel()
				for _, resp := range c.DoMultiCache(ctx, cmds...) {
					if err := resp.Error(); err != nil {
						panic(err)
					}
				}
			}(ids)
		}
	}
}
```

It looks like that the problem is not a leak but an underestimation of memory usage. Therefore, I think, at this point, reducing the `CacheSizeEachConn` option can relieve your memory.

**Comment by rueian** [comment]
Hi @NeoHuang, hope you are doing well. Did reducing the CacheSizeEachConn option relieve your memory usage?

**Comment by rueian** [comment]
Staled. Please feel free to reopen the issue if needed.
