### ISSUE TITLE
Improve `Vector()`  API

### ISSUE THREAD

**Issue by h0rv** [redis/rueidis#405]
I tried a little too long trying to find a bug while relying a little too much on ChatGPT. Nonetheless, I think this API can be improved from to:

```go
func (c FtCreateFieldAs) Vector(algo string, nargs int64, args ...string) FtCreateFieldFieldTypeVector {
...
}
```

```go
func (c FtCreateFieldAs) Vector(algo string, args []string) FtCreateFieldFieldTypeVector {
    nargs := len(args)
...
}
```

Would be a breaking change but I think its a better understand API to work with and with a language where the length of an array can easily be taken, seems less redundant than passing in `nargs`.

**Comment by rueian** [comment]
Hi @h0rv, I also feel that those nargs are redundant, but Redis requires that.

From my perspective, I would like the command builder to keep doing nothing else than one-to-one command translation.

For example, if the original command is

```
FT.CREATE myidx ON JSON SCHEMA $.vector VECTOR FLAT 6 TYPE FLOAT32 DIM 768 DISTANCE_METRIC COSINE
```

I would like the corresponding syntax for the command builder is 

```go
c.B().FtCreate().Index("myidx").OnJson().Schema().FieldName("$.vector").Vector("FLAT", 6, "TYPE", "FLOAT32", "DIM", "768", "DISTANCE_METRIC", "COSINE")
```

The above generally maps the original command arguments one by one.

 I don't think the following, omitting the nargs, will looks better:

```go
c.B().FtCreate().Index("myidx").OnJson().Schema().FieldName("$.vector").Vector("FLAT", "TYPE", "FLOAT32", "DIM", "768", "DISTANCE_METRIC", "COSINE")
```

**Comment by h0rv** [comment]
Yeah I see your point. I didn't have much Redis experience before using this package so that might be why I was struggling, but I was having trouble figuring out what the 6 was. I was parsing the "6" in my head as `(FLAT 6)` like `(DIM $DIM)`. 

But yeah I agree with the 1-to-1 translation, but the 6 is only needed for the parser, but with Go we have the extra context for the number of args passed to not need it.

**Comment by rueian** [comment]
I understand your struggle. I had the same experience too. However, once you get familiar with Redis, you may start to question why the 6 is missing when you look at this:
```go
.Vector("FLAT", "TYPE", "FLOAT32", "DIM", "768", "DISTANCE_METRIC", "COSINE")
```
Or you may hesitate to add the 6 or not when you write such a command.
