### ISSUE TITLE
No documentation for Return parameter on FtSearch

### ISSUE THREAD

**Issue by ulasakdeniz** [redis/rueidis#413]
Hi, I am trying to replicate the python code described [here](https://redis.io/docs/get-started/vector-database/#2-perform-a-k-nearest-neighbors-knn-query) in Golang for my project.

```python
query = (
    Query("(*)=>[KNN 3 @vector $query_vector AS vector_score]")
    .sort_by("vector_score")
    .return_fields("vector_score", "id", "brand", "model", "description")
    .dialect(2)
)
```

I use a different model so I am sharing the Go code with my model.
Here is my attempt:

```go
total, docs, err := client.Do(ctx, client.B().FtSearch().Index("indexname").
    Query("(*)=>[KNN 3 @vector $V]").
    Return("2").Identifier("$.title").Identifier("$.name").
    Sortby("__vector_score").
    Params().Nargs(2).NameValue().NameValue("V", rueidis.VectorString32(float32Arr)).
    Dialect(2).
    Build()).AsFtSearch()
```

Outputs only $.title. If I use .As that also doesn't work. I am not sure what to put for Return count and if I'm using Identifier correctly. Would be great to have help and documentation about this.

**Comment by rueian** [comment]
Hi @ulasakdeniz,

Your code looks good to me.

I also tried your query with this snippet, and it worked as expected.

```go
package main

import (
	"context"
	"fmt"
	"github.com/redis/rueidis"
	"github.com/redis/rueidis/om"
)

type Example struct {
	Key   string    `json:"key" redis:",key"` // the redis:",key" is required to indicate which field is the ULID key
	Ver   int64     `json:"ver" redis:",ver"` // the redis:",ver" is required to do optimistic locking to prevent lost update
	Title string    `json:"title"`            // both NewHashRepository and NewJSONRepository use json tag as field name
	Name  string    `json:"name"`
	Vec   []float64 `json:"vec"`
}

func main() {
	ctx := context.Background()
	c, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:6379"}})
	if err != nil {
		panic(err)
	}
	repo := om.NewJSONRepository("my_example", Example{}, c)
	fmt.Println(repo.CreateIndex(ctx, func(schema om.FtCreateSchema) rueidis.Completed {
		return schema.FieldName("$.vec").As("vec").Vector("FLAT", 6, "TYPE", "FLOAT64", "DIM", "8", "DISTANCE_METRIC", "COSINE").Build()
	}))
	exp := repo.NewEntity()
	exp.Title = "my_title"
	exp.Name = "my_name"
	exp.Vec = []float64{1, 1, 1, 1, 1, 1, 1, 1}
	fmt.Println(exp.Key)
	fmt.Println(repo.Save(ctx, exp))

	cmd := c.B().FtSearch().Index("jsonidx:my_example").Query("(*)=>[KNN 3 @vec $V]").
		Return("2").Identifier("$.title").Identifier("$.name").
		Sortby("__vec_score").
		Params().Nargs(2).NameValue().NameValue("V", rueidis.VectorString64([]float64{1, 1, 1, 1, 1, 1, 1, 1})).
		Dialect(2).Build()

	n, records, err := c.Do(ctx, cmd).AsFtSearch()
	fmt.Println(n, err)
	for _, r := range records {
		fmt.Println(r.Key)
		fmt.Println(r.Doc)
	}
}
```

It outputted both `$.title` and `$.name`. I ran the snippet against the `redis/redis-stack:7.2.0-v4` docker container.

What error did you receive when using `AsFtSearch`?

**Comment by ulasakdeniz** [comment]
Hi @rueian, thanks a lot for this great example! This works for me (changed to HNSW). After using your code and debugging I found out it was my mistake that I wasn't saving name field for some entities, solved it now.

I noticed 2 things though with provided code:

1. If I use `As` then I get ``:
```go
cmd := c.B().FtSearch().Index("jsonidx:my_example").Query("(*)=>[KNN 3 @vec $V]").
    Return("2").Identifier("$.title").As("title").Identifier("$.name").As("name").
    Sortby("__vec_score").
    Params().Nargs(2).NameValue().NameValue("V", rueidis.VectorString64([]float64{1, 1, 1, 1, 1, 1, 1, 1})).
    Dialect(2).Build()
```
Outputs `0 RETURN path AS name - must be accompanied with NAME`
2. If I use object mapper then I get `EOF` error.
```go
n, records, err := repo.Search(ctx, func(schema om.FtSearchIndex) rueidis.Completed {
    return schema.Query("(*)=>[KNN 3 @vec $V]").Return("2").Identifier("$.title").Identifier("$.name").
	Sortby("__vec_score").
	Params().Nargs(2).NameValue().NameValue("V", rueidis.VectorString64([]float64{1, 1, 1, 1, 1, 1, 1, 1})).
	Dialect(2).Build()
})

fmt.Println(n, err)
for _, r := range records {
    fmt.Println(r.Key)
    fmt.Println(r.Name)
    fmt.Println(r.Title)
}
```

Outputs: 0 EOF

Let me know if I miss something.

**Comment by rueian** [comment]
Hi @ulasakdeniz,

To change the returned field names, the `num` parameter of the `RETURN` keyword should be set correctly.

As per redis documentation [noted](https://redis.io/commands/ft.search/):
<img width="687" alt="image" src="https://github.com/redis/rueidis/assets/2727535/c4314909-55d1-411d-8a0e-c584d0d35492">

> `num` is the number of attributes following the keyword

The `num` should be filled with how many arguments following the `RETURN` keyword. Therefore, the correct command for redis for your case should be:
```redis
RETURN 6 $.title AS title $.name AS name
```
and the corresponding syntax for the command builder should be:
```go
Return("6").Identifier("$.title").As("title").Identifier("$.name").As("name")
```

I understand that this `num` is quite unfriendly for developers, but that is a convention required by redis.

In terms of the `repo.Search`, unfortunately, it can't work with field remapping, because it won't know how to map unexpected returned fields back to the original struct definition.

The following snippet should work instead:
```go
n, records, err := repo.Search(ctx, func(schema om.FtSearchIndex) rueidis.Completed {
    return schema.Query("(*)=>[KNN 3 @vec $V]").
	Sortby("__vec_score").
	Params().Nargs(2).NameValue().NameValue("V", rueidis.VectorString64([]float64{1, 1, 1, 1, 1, 1, 1, 1})).
	Dialect(2).Build()
})

fmt.Println(n, err)
for _, r := range records {
    fmt.Println(r.Key)
    fmt.Println(r.Name)
    fmt.Println(r.Title)
}
```

**Comment by ulasakdeniz** [comment]
Hi @rueian thank you so much for all the explanation and help! I made it work with the suggestions you sent. Appreciate the effort you put into this repo.
