### ISSUE TITLE
pipe.DoMulti can get stuck in goroutine spawned in `abort`

### ISSUE THREAD

**Issue by akallu** [redis/rueidis#416]
We had a Redis cluster of ours get slammed and saw a bunch of downstream timeouts etc., and some of our application pods (roughly like 25% of them) got into a weird state where we see a bunch of goroutines spawned inside pipe.DoMulti's `abort`, stuck trying to receive from a channel. I found this out by taking a goroutine dump and saw a bunch of the below:
```
goroutine 62049000 [chan receive, 754 minutes]:
github.com/redis/rueidis.(*pipe).DoMulti.func2(0x0?)
	/go/pkg/mod/github.com/redis/rueidis@v1.0.10/pipe.go:934 +0x3a
created by github.com/redis/rueidis.(*pipe).DoMulti in goroutine 62038499
	/go/pkg/mod/github.com/redis/rueidis@v1.0.10/pipe.go:932 +0x829
```

I went about this investigation because I saw that some pods of ours had like 4x elevated CPU util vs others- and the only difference I could discern between the pods was this.

**Comment by rueian** [comment]
Hi @akallu,

Thank you for pointing to the problematic code. Those goroutines are mandatory and responsible for recycling responses to aborted `DoMulti` requests which are aborted by their context deadline. Did you observe any abnormal events on your redis cluster just before the symptom you describe that can contribute to their overdue context deadline?

On the other hand, rueidis@v1.0.10 is too old and the problematic code is already outdated. I would recommend you upgrade to the latest version first.

**Comment by rueian** [comment]
Hi @akallu,

Did you still observe the stuck after upgrading to the latest version?

**Comment by rueian** [comment]
Hi @akallu,

Please reopen this issue if you still observe the stuck with the latest version.
