### ISSUE TITLE
PipelineMultiplex for cluster

### ISSUE THREAD

**Issue by salarali** [redis/rueidis#417]
Currently `PipelineMultiplex` has no effect for cluster. For cluster, you create 1 tcp connection per redis instance. Would it be possible to increase that value? 

I have issues on the client side with timeout issues. Each client is making around 15k to 20k requests a second. Cluster side is 14 redis instances. Each call is an exec call, that contains 2 redis ops. 

```
	redis, err = rueidis.NewClient(rueidis.ClientOption{
		InitAddress:  <ips>,
		Dialer:       net.Dialer{KeepAlive: -1}, // To disable pings
		DisableRetry: true,
		DisableCache: true,
		ShuffleInit:  true,
		MaxFlushDelay: 20 * time.Microsecond,
	})
```
Using version v1.0.23

**Comment by rueian** [comment]
Hi @salarali,

I am afraid simply increasing the value would not solve your problem. Handling 1~2k requests a second per TCP connection seems not to be a big deal if your machine is powerful enough.

Anyway, if increasing the `PipelineMultiplex` will help then we can make the cluster client respect `PipelineMultiplex` in future releases.

**Comment by salarali** [comment]
Worth a try from my end. I have been increasing the size of the redis cluster and haven't had much luck in reducing the timeouts. The client machines are pretty beefy so compute shouldn't be an issue.
