### ISSUE TITLE
[BUG] rueidis.ParseURL() cannot parse unix address

### ISSUE THREAD

**Issue by IrineSistiana** [redis/rueidis#424]
Reproduction:

```go
rueidis.ParseURL("unix:///run/redis/redis-server.sock?db=0") 
```

Returns `redis: invalid URL path: /run/redis/redis-server.sock`

Cause:

I think this is bucause this part of code does not consider that, if it is a unix addr, the unix addr will be the url.Path instead of the db number.

https://github.com/redis/rueidis/blob/0fac21f739d3c717a9da35be7d2cd6f6c2e1ab38/url.go#L60-L66

**Comment by rueian** [comment]
Hi @IrineSistiana,

Thank you for the fix!
