### ISSUE TITLE
Align `go-redis` `JSONCmdable`

### ISSUE THREAD

**Issue by unknowntpo** [redis/rueidis#432]
`go-redis` added supports for `JSON` in 9.3.0, we may need to add the adapter for it.

Reference: 
- [go-redis: Release 9.3.0](https://github.com/redis/go-redis/releases/tag/v9.3.0)
- [JSONCmdable](https://github.com/redis/go-redis/blob/73c879df57f61fe7d231f9248f3c448ace37bd77/json.go#L14)

**Comment by DestroyerAlpha** [comment]
https://github.com/redis/rueidis/pull/459 PR closes this issue right?

**Comment by rueian** [comment]
Yeap.
