### ISSUE TITLE
Add documentation regarding Replica nodes

### ISSUE THREAD

**Issue by DestroyerAlpha** [redis/rueidis#435]
We seem to have added support for Replica Reads in ClusterClient. The documentation for how to properly set it up is still missing. Adding it would help consumers from integrating it effectively.

**Comment by DestroyerAlpha** [comment]
@rueian How do we know here which address belongs to the Replica?

**Comment by rueian** [comment]
Hi @DestroyerAlpha,

We don't need to know which address belongs to replicas here. Rueidis uses `CLUSTER SLOTS` or `CLUSTER SHARDS` to get replica addresses from the provided `InitAddress`.

**Comment by erdemtuna** [comment]
I want to work on this issue. I thought over the task, however, I could not grasp where to begin, how to do, etc. I would work on the issue if you could guide me on it.

**Comment by rueian** [comment]
> ```go
> 	client, err := rueidis.NewClient(rueidis.ClientOption{
> 		InitAddress: []string{"127.0.0.1:7001", "127.0.0.1:7002", "127.0.0.1:7003"},
> 		SendToReplicas: func(cmd rueidis.Completed) bool {
> 			return cmd.IsReadOnly()
> 		},
> 	})
> ```

Hi @erdemtuna,

I think this issue can be solved by simply adding the follosing snippet to the section https://github.com/redis/rueidis?tab=readme-ov-file#redis-cluster-single-redis-and-sentinel:

```go
	client, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{"127.0.0.1:7001", "127.0.0.1:7002", "127.0.0.1:7003"},
		SendToReplicas: func(cmd rueidis.Completed) bool {
			return cmd.IsReadOnly()
		},
	})
```

You may additionally attach a refined comment to the snippet from https://github.com/redis/rueidis/blob/16d5f135a57f14205bab0850108c86e10913f56c/rueidis.go#L78.
