### ISSUE TITLE
Received unknown message type: 13 error 

### ISSUE THREAD

**Issue by abdullahskartal** [redis/rueidis#438]
We are using Rueidis for a while on high RPM server. Recently, we are getting error from some of Redis commands.

We are using ZRange, ZRem, ZAdd,  Zrevrange, ZCount, SAdd, SRem, SGet commands and so far we got error from SRem and ZRange commands.

The error is: **Received unknown message type: 13**

This is not happening all the time so I suspect the auto pipelining.

go version: 1.21.1
rueidis version v1.0.25

The implementation sample:

```
import (
	"context"
	"crypto/tls"
	"fmt"
	"strconv"
	"sync"

	"github.com/redis/rueidis"
)

const ADDR = ""

var tlsConfig = func() *tls.Config {
	return &tls.Config{
		MinVersion: tls.VersionTLS12,
	}
}()

var client rueidis.Client
var err error

func init() {
	client, err = rueidis.NewClient(rueidis.ClientOption{
		TLSConfig:   tlsConfig,
		InitAddress: []string{ADDR},
	})
	if err != nil {
		panic(err)
	}
}

func delete(ctx context.Context, id string, samples []uint64) {
	var wg sync.WaitGroup

	for _, sample := range samples {
		wg.Add(1)
		go func(sample uint64) {
			defer wg.Done()
			if _, err := SRem(ctx, id, strconv.FormatUint(sample, 10)); err != nil {
				fmt.Println(err)
			}
		}(sample)
	}

	wg.Wait()
}

func SRem(ctx context.Context, key string, members ...string) (val int64, err error) {
	return client.Do(ctx, client.B().Srem().Key(key).Member(members...).Build()).AsInt64()
}

func ZRange(ctx context.Context, key, start, stop string) (val []string, err error) {
	return client.Do(ctx, client.B().Zrange().Key(key).Min(start).Max(stop).Build()).AsStrSlice()
}

```

**Comment by rueian** [comment]
Hi @abdullahskartal,

This could be a bug in our protocol parser and may need a special build for debugging. Could you help run a special build that will carry out more information from the error? Or could you also try enabling the `AlwaysPipelining` option to see if the error occurs again?

Also, this could be related to your data and the Redis version. Could you briefly describe which Redis version you used and how your data in the responses of ZRange and SGet look like? For example, How large are they?

**Comment by abdullahskartal** [comment]
Hey @rueian

> Could you help run a special build that will carry out more information from the error?

Sure I can.

> Or could you also try enabling the AlwaysPipelining option to see if the error occurs again?

Ofc, I'm going to change the config.

> Could you briefly describe which Redis version you used

Redis version: redis_version:7.0.7(AWS MemoryDB)

> how your data in the responses of ZRange and SGet look like?

ZRange result count is 216045 for error record and all records are mongo object id. like 65955c50de7446c532159a8d 
ZRange and SGet result count could be millions btw. Our data size is huge and so is our traffic.

**Comment by rueian** [comment]
Hi @abdullahskartal,

Thank you for the information. I will try to reproduce it on my side as well.

And the debug version is ready `v1.0.26-debug438`, which will carry the buffer content in the error (https://github.com/redis/rueidis/commit/a2e2e7d32b54c0160258f5142d6ffc85aff4c972). Before sharing the content with me for further debugging, please make sure that the shared content doesn't disclose any sensitive data.

**Comment by abdullahskartal** [comment]
Hey @rueian thanks for help. 

I just activate the `AlwaysPipelining` flag and deployed the new debug version. I'll share the results when an error occurs.

**Comment by rueian** [comment]
Hi @abdullahskartal,

Did the error occur again?

**Comment by abdullahskartal** [comment]
Hi @rueian, the error has not reoccurred yet. We can close the issue and I can create new issue when its happen again.

Thanks again for helps.
