### ISSUE TITLE
Move OpenTelemetry dependencies to `rueidisotel` subpackage

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#447]
Currently, the otel dependencies live in the root `go.mod`:
https://github.com/redis/rueidis/blob/3b113fc63c830d007d67719767614e02c9879f43/go.mod#L7-L11

There are two problems with this approach:
1. It requires go 1.20 and upwards.
2. It introduces unnecessary dependencies if users don't use `rueidisotel`

It will be better to move those dependencies to  `rueidisotel`'s own go.mod like what go-redis did:

https://github.com/redis/go-redis/blob/531f06861b26fc01b1b75f777d7155d286b0943c/extra/redisotel/go.mod#L5-L15

**Comment by shouryagautam** [comment]
Hey can i work on this?

**Comment by rueian** [comment]
> Hey can i work on this?

Sure!
