### ISSUE TITLE
Add support for Streaming Reads and Writes to redis

### ISSUE THREAD

**Issue by DestroyerAlpha** [redis/rueidis#450]
https://ammar.io/blog/high-performance-redis-and-go
Should we consider adding similar support in rueidis?

**Comment by rueian** [comment]
Sure! Thank you for sharing the great blog and the great redjet.

I would also like rueidis to have streaming read/write abilities. I believe we can add those abilities to the `DedicatedClient` interface.

**Comment by rueian** [comment]
Stream read has been implemented in the #460. But I currently have no idea how to bring streaming write into the command builder interface. If someone has a better idea, please reopen this issue.
