### ISSUE TITLE
Move the `ulid` dependency to the `om` and `rueidisaside` subpackages

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#452]
Following the https://github.com/redis/rueidis/issues/447,

We should continue to reduce unnecessary dependencies for users.

The `github.com/oklog/ulid/v2` is only used in the `om` and the `rueidisaside`. It will be better to move the dependency to their separate go.mod.

**Comment by DestroyerAlpha** [comment]
Added a PR that fixes this

**Comment by rueian** [comment]
Thanks @DestroyerAlpha!
