### ISSUE TITLE
occurs deadlock when using rueidislock

### ISSUE THREAD

**Issue by lenonqing** [redis/rueidis#457]
`m.mu.Lock()` occurs deadlock when executing `locker.waitgate` once.
![image](https://github.com/redis/rueidis/assets/4057544/c8c3ecc0-a000-4595-bb7f-5e946e0c663a)

But It didn't occurs again.

rueidis version is `v1.0.22-go1.18`

**Comment by rueian** [comment]
Hi @lenonqing, did you have the goroutines dump showing where the goroutine was stuck?

**Comment by lenonqing** [comment]
@rueian I didn't have the goroutine stack，but show stuck in `m.mu.Lock`

**Comment by rueian** [comment]
Hi @lenonqing, I have found what could have caused the deadlock. The fix will be landed in the next release.

**Comment by lenonqing** [comment]
@rueian OK,Thanks!
