### ISSUE TITLE
Add key:arg pair to Arbitrary

### ISSUE THREAD

**Issue by matsuev** [redis/rueidis#464]
client.B().Arbitrary("ANY", "CMD").Keys("k1", "k2").Args("a1", "a2").Build()
will result into [ANY CMD k1 k2 a1 a2]

But, command Zadd wait aguments as key:arg pair
[ZADD NAME k1 a1 k2 a2 k3 a3....]

**Comment by rueian** [comment]
Hi @matsuev,

The k1, k2, and k3 should be treated as Zadd arguments, therefore the syntax should be:
```go
client.B().Arbitrary("ZADD").Keys("NAME").Args("k1", "a1", "k2", "a2", "k3", "a3").Build()
```

**Comment by rueian** [comment]
Hi @matsuev, as answered above. Feel free to reopen this if needed. Thanks.
