### ISSUE TITLE
Add support for RedisBloom

### ISSUE THREAD

**Issue by DestroyerAlpha** [redis/rueidis#477]
Ref: https://github.com/RedisBloom/RedisBloom

**Comment by rueian** [comment]
Hi @DestroyerAlpha,

RedisBloom is already supported:

```go
client.B().BfReserve().Key("bikes:models").ErrorRate(0.001).Capacity(1000000)
```

**Comment by DestroyerAlpha** [comment]
Can we add documentation for it? Wasn't evident. Closing this issue then.
