### ISSUE TITLE
panic after upgrade to 1.0.29

### ISSUE THREAD

**Issue by batazor** [redis/rueidis#478]
<img width="1452" alt="Screenshot 2024-02-24 at 22 11 20" src="https://github.com/redis/rueidis/assets/1643797/805bb2a0-5ce2-4e11-90e6-c7682f449035">
<img width="1452" alt="Screenshot 2024-02-24 at 22 19 38" src="https://github.com/redis/rueidis/assets/1643797/ad7a4b4f-54d6-44ec-a2ab-b08fc4458e14">

**Comment by rueian** [comment]
Hi @batazor, thanks! This will be fixed soon with a new release!

**Comment by rueian** [comment]
It looks like the tests of rueidisotel and other sub packages do not run correctly on the CI. Now I run them manually for the next release. This will also be fixed later.
