### ISSUE TITLE
GraphConstraintCreate/Delete Seems incomplete

### ISSUE THREAD

**Issue by bcotton** [redis/rueidis#483]
Using RedisGraph I'm trying to add a constraint:
```
GRAPH.CONSTRAINT CREATE service-model unique node Component properties 1 name
```

The return from the builder function for `GraphConstraintCreate()` returns no `Graph()` builder for the graph or the rest of the constraint.

```
{"time":"2024-02-27T19:54:53.908082495Z","level":"ERROR","msg":"Error creating unique constraint for Component","error":"wrong number of arguments for 'graph.CONSTRAINT' command"}
panic: wrong number of arguments for 'graph.CONSTRAINT' command

```

Unless I'm missing something?

**Comment by rueian** [comment]
Hi @bcotton, thank you for reporting this issue.

The command builder is generated from a copy of https://github.com/RedisGraph/RedisGraph/blob/master/commands.json.

It looks like the command definitions are incomplete as well.

Thankfully we have our copy https://github.com/redis/rueidis/blob/main/hack/cmds/commands_graph.json, we can complete the definitions there.

**Comment by rueian** [comment]
Hi @bcotton,

This fix will be released in the next few weeks. Before that, you can use the `client.B().Arbitrary()` builder instead.
