### ISSUE TITLE
Error connecting to dragonfly with syntax error

### ISSUE THREAD

**Issue by vamshiaruru** [redis/rueidis#495]
Hi every, thanks for the great library. Been using rueidis for a while now with redis and my org is considering using dragonfly as a replacement. I brought up dragonfly locally using
```
  docker run -p 6380:6379 --ulimit memlock=-1 docker.dragonflydb.io/dragonflydb/dragonfly
```
The version is
```
I20240312 21:41:01.746660     1 init.cc:70] dragonfly running in opt mode.
I20240312 21:41:01.746815     1 dfly_main.cc:627] Starting dragonfly df-v1.15.1-d6703460242ab8aa415a93f32677c5f23b5e6ec8
```
and I am running it on mac.

I try to connect to it using
```
	client, err := rueidis.NewClient(rueidis.MustParseURL("redis://@localhost:6380/0"))
	if err != nil {
		log.Fatalf("error connecting to redis: %v\n", err)
	}
```
But I get the error `syntax error`. I am using latest rueidis version (in my go mod `github.com/redis/rueidis v1.0.31`).

Am I doing anything wrong? Any help is appreciated, thanks!

**Comment by vamshiaruru** [comment]
Things seem to work fine with the `go-redis` client, if that helps.

**Comment by rueian** [comment]
Hi @vamshiaruru,

This may be helpful  https://github.com/dragonflydb/dragonfly/issues/2454

**Comment by vamshiaruru** [comment]
Hi @rueian , thansk for the response. Setting `DisableCache` to true works! Just to be clear, this means no in memory caching at all right, until dragonfly fixes their issue? Or is there something we can do to just send `CLIENT TRACKING ON` instead of `CLIENT TRACKING ON OPTIN`? 
Also, this means rueidislock with default config won't work either right, we have to disable memory caching there as well?

**Comment by vamshiaruru** [comment]
Understood, thanks for the response. I'll close this issue now.
