### ISSUE TITLE
multicore performance benchmark for client

### ISSUE THREAD

**Issue by ouvaa** [redis/rueidis#507]
wondering how does golang perform using rueidis in multi core environment e.g. 48 cores and above.

i was wondering instead of opening multiple client connection, is it possible to use 1 client connection so rueidis can do multi core and take advantage of all cpu cores.

i have a fast customized redis server but need a high performance multicore redis client.

not talking about pipelining or batching, just using 1 client connection. i'm not sure how the internal works but curious if it's designed with this in mind.

**Comment by rueian** [comment]
Hi @ouvaa,

rueidis uses two goroutines to process one connection. One for reading responses from redis, and another one for writing queued requests to redis server.

**Comment by ouvaa** [comment]
@rueian thank you. this shld be put prominently on the front page readme section.
