### ISSUE TITLE
Fix code scanning alert - Incorrect conversion between integer types

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#513]
Tracking issue for:
- [ ] https://github.com/redis/rueidis/security/code-scanning/5

**Comment by moonorange** [comment]
@rueian I'm running into a 404 error when trying to access the link. Would you mind filling me in with more details about the issue?

**Comment by rueian** [comment]
Hi @moonorange, here is the content of the link

<img width="932" alt="image" src="https://github.com/redis/rueidis/assets/2727535/7fd1b1d5-d5a8-4c3d-9d31-f59d79306234">

**Comment by rueian** [comment]
Hi @proost,

CodeQL found the `uint(uint64)` conversion issue in 3 lines of rueidisprob.

<img width="922" alt="image" src="https://github.com/redis/rueidis/assets/2727535/140e5057-7775-4989-a72e-66cfd5f7a008">

Could we just return uint64 without conversion?

**Comment by proost** [comment]
@rueian changing to uint64 is easy, but it is breaking change. 
If we care backward-compatibility, we should deprecate old methods and adding new methods. If not, change to uint64.

**Comment by rueian** [comment]
Yes, it is a breaking change, but I believe it is acceptable since most people don’t explicitly declare its return value as uint. If they don’t do that they will not be break. It they do that they can also easily fix the break.
