### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [redis/rueidis#528]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x95e28d]

goroutine 3244 [running]:
github.com/redis/rueidis.(*lru).purge(0xc0027e1200, {0xc0cb1c53c8, 0x13}, 0xc04b7fbba0)
	/home/runner/go/pkg/mod/github.com/redis/rueidis@v1.0.33/lru.go:299 +0xad
github.com/redis/rueidis.(*lru).Delete(0xc0027e1200, {0xc0dca2c340, 0x1, 0x0?})
	/home/runner/go/pkg/mod/github.com/redis/rueidis@v1.0.33/lru.go:318 +0x15f
github.com/redis/rueidis.(*pipe).handlePush(0xc000a27440, {0xc0afeaf300, 0x0?, 0xc0afeaf300?})
	/home/runner/go/pkg/mod/github.com/redis/rueidis@v1.0.33/pipe.go:640 +0x4fa
github.com/redis/rueidis.(*pipe)._backgroundRead(0xc000a27440)
	/home/runner/go/pkg/mod/github.com/redis/rueidis@v1.0.33/pipe.go:487 +0x32a
github.com/redis/rueidis.(*pipe)._background(0xc000a27440)
	/home/runner/go/pkg/mod/github.com/redis/rueidis@v1.0.33/pipe.go:342 +0x88
created by github.com/redis/rueidis.(*pipe).background.func1 in goroutine 3134
	/home/runner/go/pkg/mod/github.com/redis/rueidis@v1.0.33/pipe.go:325 +0x56
```

**Comment by rueian** [comment]
Hi @VladyslavLukyanenko,

Could you provide the `go build` command, the GOARCH, and the GOOS env variable you used for building the executable? I would like to locate where the `+0xad` points to.

**Comment by VladyslavLukyanenko** [comment]
@rueian 

go build command: go build -o ${{ env.BINARY_NAME }} cmd/productpage/main.go
GOARCH: amd64
GOOS: linux

It was built in github action, using golang version 1.22, on `runs-on: ubuntu-latest`

**Comment by VladyslavLukyanenko** [comment]
> @VladyslavLukyanenko, would you mind using the v1.0.35-dev1 to verify if the issue has been solved?

I'm going to do so, but it's the first time i see this issue over couple months of using the library, will let you know whether i spot it again

**Comment by rueian** [comment]
> > @VladyslavLukyanenko, would you mind using the v1.0.35-dev1 to verify if the issue has been solved?
> 
> I'm going to do so, but it's the first time i see this issue over couple months of using the library, will let you know whether i spot it again

Thank you for your cooperation. I will merge the mitigation and close this issue first.
