### ISSUE TITLE
will be using rueidis a lot but is there a way to have zero allocation? e.g. command etc

### ISSUE THREAD

**Issue by ouvaa** [redis/rueidis#531]
in a high performance setting, how to achieve zero alloc using rueidis? or what sort of commands will i be limited to if i need zero allocation?

p.s. : i just saw a discussion tab, pls help move this there. thx.

**Comment by rueian** [comment]
Hi @ouvaa,

The command builder of rueidis recycles all successful commands. You can treat this as an amortized zero allocation.

On the response side, All `OK` responses will not need additional allocation. For example, the benchmark of SET command in https://github.com/rueian/rueidis-benchmark shows amortized zero allocation.

**Comment by ouvaa** [comment]
@rueian ok. maybe can explore making goasm or c->goasm or somewhere along that line in future. truly hope for zero alloc.

it's fantastic as it is this rueidis package.
