### ISSUE TITLE
Test go1.22 on Github Action Matrix

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#554]
The PR https://github.com/redis/rueidis/pull/553 brings go1.22 dependencies to rueidis, so we need to test it with go1.22 as well and [Github Action Matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) can help us.

We should add a new `go-version` variable with values including 1.21 and 1.22 to the matrix:

https://github.com/redis/rueidis/blob/37fc75f938f5dae2eeda4771cb9f68f50aab9bf0/.github/workflows/build.yml#L19-L22

**Comment by mahiro72** [comment]
Hey @rueian , can I work on this one?

**Comment by LWF15** [comment]
> Hey @rueian , can I work on this one?

can i do this with you?

**Comment by JayChavan-23** [comment]
Hey @mahiro72,

I am currently working on this. If I encounter any issues, can we collaborate on it together? Alright?

**Comment by mahiro72** [comment]
@JayChavan-23 Yes, sure!

**Comment by JayChavan-23** [comment]
@rueian @mahiro72 @SoulPancake 
I’m having some trouble getting started since I’m a beginner. Can you help me by explaining where I should start and the flow I should follow? I want to try working on it by myself, but if I can't make progress in the next couple of days, I’m open to collaboration. A little heads-up would be appreciated.

Thank you!

**Comment by rueian** [comment]
> @rueian @mahiro72 @SoulPancake I’m having some trouble getting started since I’m a beginner. Can you help me by explaining where I should start and the flow I should follow? I want to try working on it by myself, but if I can't make progress in the next couple of days, I’m open to collaboration. A little heads-up would be appreciated.
> 
> Thank you!

Hi @JayChavan-23, I think the following changes are required to be made.

```diff
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index 1234567..89abcde 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,6 +14,7 @@ jobs:
       matrix:
         module: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
+        go-version: ['1.21.0', '1.22.0']
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -22,7 +23,7 @@ jobs:
       - name: Set up Go
         uses: actions/setup-go@v5
         with:
-          go-version: '1.21.0'
+          go-version: ${{ matrix.go-version }}

       - name: Test Module
         run: |
```

These changes are generated by ChatGPT.

**Comment by JayChavan-23** [comment]
Thanks for the heads-up. I'm working on it

**Comment by rueian** [comment]
Resolved by https://github.com/redis/rueidis/pull/563
