### ISSUE TITLE
"Unknown command" error when connecting to Redis cluster with authentication

### ISSUE THREAD

**Issue by totorofly** [redis/rueidis#556]
# Description:
I am encountering an "unknown command" error when attempting to connect to a Redis cluster using the rueidis client with username and password authentication. Below are the details of my setup and the error:

# Environment:

- rueidis version: v1.0.38
- Redis version: 7.0
- Go version: go1.20.4
- Operating System: MAC OS

```
// Redis configuration
fmt.Println("global.ASIR_CONFIG.Redis.Addr", global.ASIR_CONFIG.Redis.Addr)
fmt.Println("global.ASIR_CONFIG.Redis.Username", global.ASIR_CONFIG.Redis.Username)
fmt.Println("global.ASIR_CONFIG.Redis.Password", global.ASIR_CONFIG.Redis.Password)

// Initialize database
var err error
global.ASIR_RedisDB, err = rueidis.NewClient(rueidis.ClientOption{
    InitAddress: []string{global.ASIR_CONFIG.Redis.Addr},
    ShuffleInit: true,
    Username:    global.ASIR_CONFIG.Redis.Username,
    Password:    global.ASIR_CONFIG.Redis.Password,
    Dialer: net.Dialer{
        Timeout:   5 * time.Second,
        KeepAlive: 30 * time.Second,
    },
    TLSConfig: nil,
})
if err != nil {
    panic(err)
}
```

# Steps to Reproduce:

- Configure a Redis cluster with version 7.0.
- Set up username and password authentication in the Redis cluster.
- Use the rueidis client to connect to the Redis cluster using the provided configuration.

# Expected Behavior:
The client should connect to the Redis cluster successfully using the provided authentication credentials.

# Actual Behavior:
The connection attempt results in an "unknown command" error.
<img width="661" alt="图片" src="https://github.com/redis/rueidis/assets/41875799/06d2e4e5-56b7-40b4-9477-d9d06ddc0ff5">

**Comment by totorofly** [comment]
After setting AlwaysRESP2: true and DisableCache: true, I was able to connect successfully. It seems that RESP3 is not supported.

**Comment by rueian** [comment]
Hi @totorofly, RESP3 should be supported by Redis 7 unless it is modified by your vendor. Would you mind to share with us which vendor you are using?

**Comment by totorofly** [comment]
The modification has indeed been made. I am using the Redis cluster provided by Alibaba Cloud. After communication, RESP3 has been enabled.
