### ISSUE TITLE
Add IsParseErr helper

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#557]
In the PR https://github.com/redis/rueidis/pull/555, we have switched to returning an error from the old panic behavior when using a wrong parsing function to handle redis responses.

I think it would be nice if we provided an `IsParseErr` helper so that users can have more control over the error:

```go
_, err := client.Do(ctx, client.B().Get().Key("key").Build()).ToInt64()
if rueidis.IsParseErr(err) {
	//Do whatever user want
}
```

## Possible Implementations

1. Introduce a new global error instance `ParseError` and wrap it into all errors returned in the https://github.com/redis/rueidis/pull/555. And use `errors.Is` in the `IsParseErr` helper.
2. Use `strings.HasPrefix` in the `IsParseErr` helper to check if the error has the same prefix of errors returned in the https://github.com/redis/rueidis/pull/555.

**Comment by SoulPancake** [comment]
Would be happy to take this up if no other volunteers, also because it's an extension of the previous PR @rueian

**Comment by LWF15** [comment]
can I give a try

**Comment by SoulPancake** [comment]
Go ahead for sure @LWF15

**Comment by LWF15** [comment]
Hi, I currently got a bit lost here. So, I need to set a global instance ParseError in message.go and set to the error return of 555 change right? Could you give me some hint then where should I start with

**Comment by SoulPancake** [comment]
@LWF15 Basic idea is
Something like this
```
var ParseError = errors.New("rueidis: parse error")
// IsParseErr checks if the error is a parse error
func IsParseErr(err error) bool {
    return errors.Is(err, ParseError)
}

```
and in all the places where I am returning the error in message.go do something like this 
`fmt.Errorf("%w: redis message type %s is not a RESP3 int64", ParseError, typeNames[m.typ])`

**Comment by neelpatel04466** [comment]
Thanks for working on this @LWF15 and @SoulPancake. Here’s the basic idea:

Introduce a Global ParseError Instance:
```
var ParseError = errors.New("rueidis: parse error")
``` 
Implement IsParseErr Helper Function:
```
func IsParseErr(err error) bool {
    return errors.Is(err, ParseError)
}
``` 
```
_, err := client.Do(ctx, client.B().Get().Key("key").Build()).ToInt64()
if rueidis.IsParseErr(err) {
    // Handle parse error
}
``` 
Looking forward to your PR with these changes!

**Comment by neelpatel04466** [comment]
Hi @LWF15,

Great progress on this feature! Here are a few steps to help you finalize the implementation:

1. **Define the Global ParseError Instance:**
   - Add the following code in `message.go`:

     ```go
     var ParseError = errors.New("rueidis: parse error")
     ```

2. **Update Error Returns:**
   - Modify the error returns in `message.go` to wrap errors with `ParseError`. For example:

     ```go
     return fmt.Errorf("%w: redis message type %s is not a RESP3 int64", ParseError, typeNames[m.typ])
     ```

3. **Implement the IsParseErr Helper Function:**
   - Add this function to help users identify parse errors:

     ```go
     func IsParseErr(err error) bool {
         return errors.Is(err, ParseError)
     }
     ```

Here’s an example of how your code should look:

```go
package rueidis

import (
    "errors"
    "fmt"
)

var ParseError = errors.New("rueidis: parse error")

func IsParseErr(err error) bool {
    return errors.Is(err, ParseError)
}

// In message.go, wrap errors like this:
func someFunction() error {
    // Your existing code
    return fmt.Errorf("%w: redis message type %s is not a RESP3 int64", ParseError, typeNames[m.typ])
}

**Comment by LWF15** [comment]
Thank You!

**Comment by rueian** [comment]
Solved by https://github.com/redis/rueidis/pull/564
