### ISSUE TITLE
Initialize the Redis connection lazily

### ISSUE THREAD

**Issue by ash2k** [redis/rueidis#558]
If Redis is down (e.g. temporarily), my application fails to start. It'd be more consistent that client construction was separate from actually trying to talk to Redis. If Redis is available, then application starts fine, then Redis becomes unavailable and Redis I/O just fails - application still works otherwise. Would be more consistent if startup of my application was not affected by Redis availability.

Would it be possible to change the behavior like this? Try to connect to Redis asynchronously or on first use?

**Comment by SoulPancake** [comment]
@ash2k like this https://github.com/redis/rueidis/issues/489?

**Comment by ash2k** [comment]
Yes, it's the same issue. Thanks.
