### ISSUE TITLE
VSCode appends `cmds.Completed` whenever `cmds.Builder` is accessed

### ISSUE THREAD

**Issue by Delicious-Bacon** [redis/rueidis#58]
I'm using the latest VSCode

Whenever I use `cmds.Builder` and accept any of the suggested functions, VSCode appends `cmds.Completed` before the `cmds.Builder`.

It's best to explain it visually:
![Code_Y06d4tSdJi](https://user-images.githubusercontent.com/78080236/176994422-f08f9b2b-30fb-47e7-a1d5-df7b738db5b5.gif)

**Comment by rueian** [comment]
Oh, it isn't very pleasant. Thank you for reporting this. I will see what I can do.

However, I believe this is a bug of the vscode golang extension, because the `cmds.Completed` is not exported and the extension just produces a code that wouldn't be compiled.

**Comment by Delicious-Bacon** [comment]
> ...the `cmds.Completed` is not exported and the extension just produces a code that wouldn't be compiled.

It is exported if it is uppercase, isn't it...? 🤔

**Comment by rueian** [comment]
> It is exported if it is uppercase, isn't it...? 🤔

No, it isn't. It lives in an internal package. Users are not allowed to import and use it directly.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/2727535/177004345-6aacfa76-32c9-46a9-8c0f-37283c79acfe.png">

**Comment by Delicious-Bacon** [comment]
I see, thanks for the explanation!

And thank you for looking into it! ❤️

**Comment by rueian** [comment]
Hi @Delicious-Bacon, 

This issue is related to the official Go language server and may not have a solution in a short time.

Instead of using another IDE/Editor, you can just not access `cmds.Builder` in the `client.Do`. For example, preparing the command beforehand.

```golang
cmd := client.B().Get().Key("mykey").Build()
client.Do(ctx, cmd)
```
