### ISSUE TITLE
Make DedicatedClient.Do return errors after being recycled

### ISSUE THREAD

**Issue by FZambia** [redis/rueidis#586]
Hello @rueian !

I got the following panic traceback in Centrifuge:

```
panic: DedicatedClient should not be used after recycled

goroutine 169 [running]:
github.com/redis/rueidis.(*dedicatedSingleClient).check(...)
  /Users/alexander.emelin/go/pkg/mod/github.com/redis/rueidis@v1.0.38/client.go:239
github.com/redis/rueidis.(*dedicatedSingleClient).Do(0x140017121b0, {0x1038f4550, 0x103f80b80}, {0x14000b088c0, 0x3000, 0x8000})
  /Users/alexander.emelin/go/pkg/mod/github.com/redis/rueidis@v1.0.38/client.go:179 +0x168
github.com/centrifugal/centrifuge.(*RedisBroker).unsubscribe(0x1400012c200, 0x140001380a0, {0x14001775f20, 0xa})
  /Users/alexander.emelin/centrifugal/centrifuge/broker_redis.go:894 +0x514
```

It happened only once and I was not able to reproduce it again. My question is – does it indicate that I am using rueidis wrong, probably using Client after Close? Or the panic here helps to diagnose internal problems of rueidis itself?

**Comment by FZambia** [comment]
Thx! Yeah, if it indicates the use after close, then returning an error seems a better approach to me – I generally handle errors from unsubscribe operations, but panic was somewhat unexpected in this place. Most probably it will be non-trivial for me to fully get rid of use after close path.

**Comment by rueian** [comment]
Thanks @FZambia! The PR has been merged.
