### ISSUE TITLE
Index Out of Range issue in DoMultiCache function

### ISSUE THREAD

**Issue by Carcraftz** [redis/rueidis#590]
Hey! Stumbled across this (very rare) issue and thought I'd share it here in case it helps development.

panic: runtime error: index out of range [718802477] with length 29

goroutine 3414167 [running]:
github.com/redis/rueidis.(*mux).DoMultiCache.func1(0x2)
	/home/runner/go/pkg/mod/github.com/redis/rueidis@v1.0.39/mux.go:334 +0x219
github.com/redis/rueidis/internal/util.worker[...](0xce00353e60?, 0xcd49110bd0, 0xc66c1b71a0)
	/home/runner/go/pkg/mod/github.com/redis/rueidis@v1.0.39/internal/util/parallel.go:25 +0x35
created by github.com/redis/rueidis/internal/util.closeThenParallel[...] in goroutine 3411831
	/home/runner/go/pkg/mod/github.com/redis/rueidis@v1.0.39/internal/util/parallel.go:39 +0x8c

**Comment by rueian** [comment]
Hi @Carcraftz,

Could you help clarify where the `length 29` came from? Was that the number of commands you put into a `DoMultiCache` call?

**Comment by Carcraftz** [comment]
Yes, it was

**Comment by rueian** [comment]
Hi @Carcraftz,

I am still trying to find out how could this happened. According to your stack trace:
https://github.com/redis/rueidis/blob/6831b3003859d87e9fa2645ae40008b0d7e8d431/mux.go#L323-L334

The value of `batch.cIndexes[i]` at L334 was 718802477, but we only stored the index value at line L323 to the `batch.cIndexes` at L326. Have you ever called `DoMultiCache` with 718802477 commands?

**Comment by rueian** [comment]
Hi @Carcraftz,

Would you mind trying the latest [v1.0.45-alpha.1](https://github.com/redis/rueidis/releases/tag/v1.0.45-alpha.1)? The version may fix this issue because accessing stale values is impossible now. It clears all sync.Pool containers before recycling.

**Comment by rueian** [comment]
Hi @Carcraftz, v1.0.45 is out. Please just use the `v1.0.45`, no alpha.
