### ISSUE TITLE
Sample code for Generic Object Mapping hangs indefinitely

### ISSUE THREAD

**Issue by mpjunior92** [redis/rueidis#591]
### Bug
Running sample code from https://github.com/redis/rueidis/tree/main/om#generic-object-mapping using a `JSONRepository` causes the repo to hang indefinitely.

### Initial findings
`singleClient` gets stuck at `DoCache` operation:
```go
func (c *singleClient) DoCache(ctx context.Context, cmd Cacheable, ttl time.Duration) (resp RedisResult) {
retry:
	resp = c.conn.DoCache(ctx, cmd, ttl)
	if c.retry && c.isRetryable(resp.NonRedisError(), ctx) {
		goto retry // <-- execution falls here
	}
	if err := resp.NonRedisError(); err == nil || err == ErrDoCacheAborted {
		cmds.PutCacheable(cmd)
	}
	return resp
}
```
Returned error:
> "failed to fetch the cache because EXEC was aborted by redis or connection closed"

### Steps to reproduce:
- Start a redis server locally by running `redis-server` on terminal
- Copy sample code from https://github.com/redis/rueidis/tree/main/om#generic-object-mapping onto a `main.go` file
- Replace `NewHashRepository` with `NewJSONRepository`
- Run code: `go run main.go`

### Expected result
Program executes through completion without hanging.

### Environment
- **OS**: Linux matheus 6.5.0-44-generic # 44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 18 14:36:16 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- **go version**: go version go1.21.6 linux/amd64
- **Redis version**: Redis server v=7.2.5 sha=00000000:0 malloc=jemalloc-5.3.0 bits=64 build=d284576ab9ca3cc5
- **rueidis version**: v1.0.41

**Comment by rueian** [comment]
Hi @mpjunior92,

Thank you for reporting! It is indeed a bug that is being stuck. We need to exclude the case of `ErrDoCacheAborted` from `c.isRetryable()`. That is, we should fix it by making it return false when `resp.NonRedisError() == ErrDoCacheAborted`.

But the fix won't let you use the `NewJSONRepository` either. To use `NewJSONRepository`, your redis must have redisjson module installed.

**Comment by ajayd-san** [comment]
Hey, can i take this up ?

**Comment by rueian** [comment]
> Hey, can i take this up ?

Sure! Thanks!
