### ISSUE TITLE
Could Hset example can be added to cheatsheet ?

### ISSUE THREAD

**Issue by TravisBacon** [redis/rueidis#610]
I couldn't find how to set hash with rueidis.
The doc's help is also limited.

**Comment by TravisBacon** [comment]
redisClient.Do(ctx, redisClient.B().Hset().Key(useridstr).FieldValue().FieldValue("nickname", nickname).FieldValue("photopath", photopath).Build()).Error()

**Comment by rueian** [comment]
Hi @TravisBacon,

That's a great example. Would you mind opening a PR for adding it to the cheatsheet?
