### ISSUE TITLE
Rueidis making `CLIENT SETINFO` commands that are not supported by ElastiCache Redis

### ISSUE THREAD

**Issue by rahulgkatre** [redis/rueidis#620]
We have observed that our application is making `CLIENT SETINFO` commands to the Redis server hosted on AWS ElastiCache. However, these commands are not supported by ElastiCache Redis.

The `CLIENT SETINFO` command is used to set arbitrary information for the current connection. While this command is available in open-source Redis version 7.2 and up, it is not supported by ElastiCache Redis (which is on "7.1" or 7.0).

Steps to Reproduce:
1. Create an ElastiCache Redis instance (e.g. serverless) 
2. Connect to the ElastiCache Redis instance using a Rueidis client
3. The ElastiCache metric `CommandAuthorizationFailures` should increase

Potential fix:
The Rueidis client has an option for `ClientSetInfo` but there is no option to disable it entirely for support with older versions of Redis. An option can be added to the client options type to disable the execution of this command.

**Comment by rueian** [comment]
Instead of another option, I would prefer this:

```go
var DisableClientSetInfo = make([]string)
...
rueidis.NewClient(rueidis.ClientOption{
	ClientSetInfo: rueidis.DisableClientSetInfo,
})
```

**Comment by rahulgkatre** [comment]
I've been trying your suggested fix out, diff here: https://github.com/rahulgkatre/rueidis/pull/1/files

The test I added for this change passes locally but in the workflow there are failures related to data races.

**Comment by rahulgkatre** [comment]
Thanks for the help, workflows passed and I've opened the PR to this repo.
