### ISSUE TITLE
rueidislock: left a record in Redis after cancelling the context

### ISSUE THREAD

**Issue by UncleVic** [redis/rueidis#623]
I'm trying to solve a problem to prevent running of background processes from starting not only at the same time but also not earlier than once per interval.

rueidislock helps me solve the first part of the problem, but when the locking context is canceled, a record in Redis will be deleted and other instances of my app will be able to start the completed process without any interval.

My suggestion is:

1. Add an extra option
```go
type LockerOption struct {
        ...

	// KeepAlive prevents deletion of the key
	KeepAlive bool
}

type locker struct {
        ...
	keepalive bool
}
```

2. In the `monitor` function. It's line 327 now. Extend the condition:
```go
if err != ErrNotLocked && !m.keepalive {
	_ = m.script(context.Background(), delkey, key, val, deadline)
}
```

3. Add a public method 
```go
func (m *locker) Release(ctx context.Context, name string) {
	val := random()
	deadline := time.Now().Add(m.validity)

	var i int32
	for i = 0; i < m.majority; i++ {
		key := keyname(m.prefix, name, i)

		_ = m.script(context.Background(), delkey, key, val, deadline)
	}

	return
}
```

Thereafter, the remaining key will continue to live and prevent running another instances of the app

What do you think about an approach like that?

**Comment by rueian** [comment]
Hi @UncleVic,

I am wondering if you can just release the lock later:

```go
	ctx, cancel, err := locker.WithContext(context.Background(), "mylock") // use a new context.
	if err != nil {
		panic(err)
	}
	// do your work ...
	time.AfterFunc(time.Minute, cancel) // release the lock after a period.
```

**Comment by UncleVic** [comment]
Yes, you're right...
I ran some tests and everything is working as expected...

Can I ask you more?
If I have a few lockers for different gorutins, can I use a single instance of rueidis.Client for those lockers?

**Comment by rueian** [comment]
> If I have a few lockers for different gorutins, can I use a single instance of rueidis.Client for those lockers?

The best way to do that is preparing a locker instance upfront and use it in every goroutine.

Or you could do it like this:

```go
	var mu sync.Mutex
	var err error
	var client rueidis.Client

	rueidislock.NewLocker(rueidislock.LockerOption{
		ClientOption: rueidis.ClientOption{
			InitAddress: []string{"localhost:6379"},
		},
		ClientBuilder: func(option rueidis.ClientOption) (rueidis.Client, error) {
			mu.Lock()
			defer mu.Unlock()
			if client != nil {
				return client, nil
			}
			client, err = rueidis.NewClient(option)
			return client, err
		},
	})
```

**Comment by UncleVic** [comment]
I can't use a just one instance of locker. I have different options of KeyValidity for gorutines.

The last solution is similar to NewLocker. In that case, it's easy to use the constructor NewLocker and don't reinvent the wheel. 

Above, you just rewrite your own code 
```go
	var err error
	if option.ClientBuilder != nil {
		impl.client, err = option.ClientBuilder(option.ClientOption)
	} else {
		impl.client, err = rueidis.NewClient(option.ClientOption)
	}
```

What is different, except a mutex?

**Comment by rueian** [comment]
> What is different, except a mutex?

It returns the shared `client` directly if the client has been created.

**Comment by rueian** [comment]
@UncleVic do you have any questions?

**Comment by UncleVic** [comment]
No, thx a lot.
