### ISSUE TITLE
Set multiple field/value pairs for HSET

### ISSUE THREAD

**Issue by ash2k** [redis/rueidis#629]
I have code that prepares field+value pairs (as a slice of structs) in advance and then I add them to HSET like this:

```go
hsetCmd := b.client.B().Hset().Key(redisKey).FieldValue()
for _, kv := range kvs2fvs {
	hsetCmd.FieldValue(kv.field, kv.value)
}
```

`FieldValue()` just does an append. Would be nice to append the whole slice of field-values in one go. I need to reuse that slice for multiple hash keys, so I cannot just call `FieldValue()` as I construct pairs.

**Comment by rueian** [comment]
Hi @ash2k,

We will have FieldValueIter in the next version
https://github.com/redis/rueidis/pull/625

**Comment by ash2k** [comment]
Perfect! Thank you!
