### ISSUE TITLE
Hide InitAddress when connecting to a valkey cluster using NewClient()

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#635]
See the original issue: https://github.com/valkey-io/valkey-go/issues/9

**Comment by ajayd-san** [comment]
hey can i work on this?

**Comment by rueian** [comment]
> Hey can I work on this?

Sure, any help is welcome!

**Comment by JayChavan-23** [comment]
@ajayd-san  any progress you would like to share? I would love to give it a try too
