### ISSUE TITLE
Function `redirectOrNew` return `nil connection` when change node type aws redis cluster

### ISSUE THREAD

**Issue by dangngoctam00** [redis/rueidis#640]
Hello ~, 
Yesterday, while testing scale with AWS redis cluster, my application had been panic at line:
`resp = c.redirectOrNew(addr, cc, cmd.Slot(), mode).Do(ctx, cmd)` of `rueidis v1.0.43`

<img width="1155" alt="image" src="https://github.com/user-attachments/assets/0725725a-6ccb-46fb-8adc-a2630c6c8f0b">

**Redis topology**:
+ cluster enabled
+ 1 master 1 replica

**Action**: scale in node type
This error has never happened with previous testing.

After checking function `redirectOrNew`: 
```go
func (c *clusterClient) redirectOrNew(addr string, prev conn, slot uint16, mode RedirectMode) (p conn) {
	c.mu.RLock()
	cc := c.conns[addr]
	c.mu.RUnlock()
	if cc.conn != nil && prev != cc.conn {
		return cc.conn
	}
	c.mu.Lock()

	if cc = c.conns[addr]; cc.conn == nil {
		p = c.connFn(addr, c.opt)
		c.conns[addr] = connrole{conn: p, replica: false}
		if mode == RedirectMove {
			c.pslots[slot] = p
		}
	} else if prev == cc.conn {
		// try reconnection if the MOVED redirects to the same host,
		// because the same hostname may actually be resolved into another destination
		// depending on the fail-over implementation. ex: AWS MemoryDB's resize process.
		go func(prev conn) {
			time.Sleep(time.Second * 5)
			prev.Close()
		}(prev)
		p = c.connFn(addr, c.opt)
		c.conns[addr] = connrole{conn: p, replica: cc.replica}

		if mode == RedirectMove {
			if cc.replica {
				c.rslots[slot] = p
			} else {
				c.pslots[slot] = p
			}
		}
	}
	c.mu.Unlock()
	return p
}
```
it seems that the condition at `if` and `else - if` are not true, then `nil` is returned to calling. I think `c.conns` has been changed by `refresh` between the first and second lock.

Thank you.

**Comment by rueian** [comment]
Hi @dangngoctam00, thank you for your detailed report. The bug was introduced by https://github.com/redis/rueidis/commit/3139c13ca43b983f16a136238fa71deb1bd2e0a6 and will be fixed by https://github.com/redis/rueidis/pull/641

You can also use the v1.0.47-alpha.2 release for a quick fix.
