### ISSUE TITLE
Feature: remove idle connections from pool

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#651]
Currently connections in the connection pools (`spool` and `dpool`) inside a `mux` will live forever.

It would be nice if we had an option, such as `ConnIdleDuration` or a better naming, to clean connections that are idle for a long time to reduce memory usage.

**Comment by abuzaforfagun** [comment]
I am interested in working on this issue.

**Comment by proost** [comment]
@rueian 
Does need option to min size of connection pool? making a new connection is expensive. If all connections is closed, can be harmful to latency sensitive apps. current pool only support cap size.

**Comment by rueian** [comment]
> @rueian Does need option to min size of connection pool? making a new connection is expensive. If all connections is closed, can be harmful to latency sensitive apps. current pool only support cap size.

Yes, there should be an option for that.
