### ISSUE TITLE
Bug: FT.AlterIndex options doesn't support multiple options

### ISSUE THREAD

**Issue by imvtsl** [redis/rueidis#654]
`alter.Schema().Add().Field("$.Nested.F1").Options("TEXT").Build()` works as in the test case, however
`alter.Schema().Add().Field("$.Nested.F1").Options("TEXT SORTABLE").Build()` fails with `Invalid field type for field '$.Nested.F1\'.` error.

This is probably caused by the incorrect command definitions. The options should be marked as "multiple": true:

[rueidis/hack/cmds/commands_search.json](https://github.com/redis/rueidis/blob/25821d0444e88e344cd27e66d7c9b4f27da7c580/hack/cmds/commands_search.json#L357-L360)

 { 
   "name": "options", 
   "type": "string" 
 }

**Comment by rueian** [comment]
After updating the json file, you can run `go generate` to update the generated code.

**Comment by imvtsl** [comment]
Thank you for the info.
