### ISSUE TITLE
Question: In rueidislock lua script, set and then get immediately, but the return value of get is not used. What is the purpose of get?

### ISSUE THREAD

**Issue by win5do** [redis/rueidis#663]
https://github.com/redis/rueidis/blob/372da2f977b21735e6bcd9edac386264175a8471/rueidislock/lock.go#L478

**Comment by rueian** [comment]
We need these GETs to enable [client tracking](https://redis.io/docs/latest/commands/client-tracking/) so that we can receive notifications when others change them.
