### ISSUE TITLE
Hashmap invalidation of specific fields in client side cache

### ISSUE THREAD

**Issue by CariappaKGanapathi** [redis/rueidis#673]
Currently, when a hset/hdel operation takes place, the entire key along with all the fields is purged from the lru, it would be beneficial if the specific field was only purged on such operations. Not sure why this limitation is in place. Please help me understand if this is even possible to be notified through redis in the first place.

**Comment by rueian** [comment]
Hi @CariappaKGanapathi,

Redis only tracks changes at key levels as well as notifications it sends, therefore we have no choice but to purge the entire key.
