### ISSUE TITLE
Checksum errors for 1.0.50?

### ISSUE THREAD

**Issue by ankon** [redis/rueidis#684]
I have a dependabot update for rueidis (created Dec 2, 9:17 AM GMT+1), and when I now check out the branch to look at the update I get a checksum mismatch. Anything going on here?

```
$ go mod vendor
verifying github.com/redis/rueidis@v1.0.50: checksum mismatch
	downloaded: h1:nCadAhXRuxnV5DSUyQ81hSN2SX2moj6v+o1mUGTZn+w=
	go.sum:     h1:UdsB/2EadJMGFIUuzxqFuWM2BSjXt8jYtml6eXkhJLE=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by rueian** [comment]
Hi @ankon,

I think that was caused by the fact that I re-tagged v1.0.50 once to include a missing commit. The first release of v1.0.50 didn't include the commit https://github.com/redis/rueidis/commit/5965fb92e4733fbb5f3dcc2c25ad226d72c6ce7b.

But you can try v1.0.51 now.

**Comment by ankon** [comment]
Thanks!

I think go doesn't like retagging that much, better to just respin a release indeed. Numbers are (generally) cheap and plentiful :)
