### ISSUE TITLE
How to subscribe to keyspace notifications

### ISSUE THREAD

**Issue by jo-me** [redis/rueidis#686]
Hi,

whats the proper way to receive keyspace notifications as described in https://redis.io/docs/latest/develop/use/keyspace-notifications/ ?

I managed to receive notifications via:
```
client.Receive(context.Background(), client.B().Psubscribe().Pattern("__key*__:*").Build(), func(msg rueidis.PubSubMessage) {
// handle message
}
```

How do I set the _notify-keyspace-events_ option?
The following compiles, but I don't think it works (and also feels wrong):
`client.Do(ctx, client.B().ConfigSet().ParameterValue().ParameterValue("notify-keyspace-events", "AKE").Build())`

Thanks for advice
Jochen

Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by rueian** [comment]
Hi @jo-me,

The notify-keyspace-events option should usually be set in your `redis.conf` file which your redis server reads during startup, but it is also ok to set the option in your application via CONFIG SET.

Here is an example:

```go
package main

import (
	"context"
	"fmt"
	"github.com/redis/rueidis"
	"strconv"
)

func main() {
	c, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{"127.0.0.1:6379"},
	})
	if err != nil {
		panic(err)
	}
	defer c.Close()

	// this set should usually set in your redis.conf
	err = c.Do(context.Background(), c.B().ConfigSet().ParameterValue().ParameterValue("notify-keyspace-events", "KEA").Build()).Error()
	if err != nil {
		panic(err)
	}

	go func() {
		for i := 0; ; i++ {
			key := strconv.Itoa(i)
			c.Do(context.Background(), c.B().Set().Key(key).Value(key).Build())
		}
	}()

	err = c.Receive(context.Background(), c.B().Psubscribe().Pattern("__key*__:*").Build(), func(msg rueidis.PubSubMessage) {
		fmt.Println(msg.Pattern, msg.Channel, msg.Message)
	})
	fmt.Println(err)
}
```

**Comment by jo-me** [comment]
Thanks for confirming!
