### ISSUE TITLE
Consider retry not only all read commands with DoMulti on error MOVED / ASK / TRYAGAIN / ...

### ISSUE THREAD

**Issue by wyxloading** [redis/rueidis#696]
Recently we experienced a redis cluster scaling, involve with cluster slot migrating, master-slave switching.

We got some errors return by `DoMulti` like:
- `MOVED {slot} {ip:port}`
- `ASK {slot} {ip:port}`

We are using rueidis v1.0.49. After checking driver source, we believe that behavior is associated with method `clusterClient.doMulti` 

https://github.com/redis/rueidis/blob/main/cluster.go#L733-L769

We used go-redis/v8 before and switch to rueidis recently. Checked go-redis and it does do retry not only read command. 

https://github.com/redis/go-redis/blob/v8/cluster.go#L771-L852

Wondering if rueidis can support these situations ?

If we add some retry with invoking DoMulti, we may can not recycle the `Completed` Object cause we need to `Pin` that for protentially retry. Also we have to do much more code to send command to NODE with ip:port the error return

**Comment by rueian** [comment]
Hi @wyxloading,

Thank you for raising this issue and looking into the source.

Yes, I think we should support the situation. Actually the `doMulti` you mentioned is optional. It is an optional optimization if all your commands go to a single connection, but unfortunately, it doesn't handle the complex `MOVED` and `ASK` situations.

So the solution I think is just to delete the `doMulti` and the entry of the optimization and let the rest normal path handle the retry correctly. Delete the following: https://github.com/redis/rueidis/blob/2246f91cf874bc3131eead363d0ad239a1df5903/cluster.go#L678-L683

Since you already looked into the source, would you also like to contribute?

**Comment by wyxloading** [comment]
ok, i would test that ASAP

**Comment by rueian** [comment]
Hi @wyxloading,

Thanks! Let me know if you have any problems. And I just noticed that `_pickMulti` function also needs to be updated to:

```go
func (c *clusterClient) _pickMulti(multi []Completed) (retries *connretry, last uint16, toReplica bool) {
	last = cmds.InitSlot
	init := false

	for _, cmd := range multi {
		if cmd.Slot() == cmds.InitSlot {
			init = true
			break
		}
	}

	c.mu.RLock()
	defer c.mu.RUnlock()

	count := conncountp.Get(len(c.conns), len(c.conns))

	if !init && c.rslots != nil && c.opt.SendToReplicas != nil {
		for _, cmd := range multi {
			var p conn
			if c.opt.SendToReplicas(cmd) {
				p = c.rslots[cmd.Slot()]
			} else {
				p = c.pslots[cmd.Slot()]
			}
			if p == nil {
				return nil, 0, false
			}
			count.m[p]++
		}

		retries = connretryp.Get(len(count.m), len(count.m))
		for cc, n := range count.m {
			retries.m[cc] = retryp.Get(0, n)
		}
		conncountp.Put(count)

		for i, cmd := range multi {
			last = cmd.Slot()

			var cc conn
			if c.opt.SendToReplicas(cmd) {
				toReplica = true
				cc = c.rslots[cmd.Slot()]
			} else {
				cc = c.pslots[cmd.Slot()]
			}

			re := retries.m[cc]
			re.commands = append(re.commands, cmd)
			re.cIndexes = append(re.cIndexes, i)
		}
		return retries, last, toReplica
	}

	inits := 0
	for _, cmd := range multi {
		if cmd.Slot() == cmds.InitSlot {
			inits++
			continue
		}
		if last == cmds.InitSlot {
			last = cmd.Slot()
		} else if init && last != cmd.Slot() {
			panic(panicMixCxSlot)
		}
		p := c.pslots[cmd.Slot()]
		if p == nil {
			return nil, 0, false
		}
		count.m[p]++
	}

	if last == cmds.InitSlot {
		// if all commands have no slots, such as INFO, we pick a non-nil slot.
		for i, p := range c.pslots {
			if p != nil {
				last = uint16(i)
				count.m[p] = inits
				break
			}
		}
	}

	retries = connretryp.Get(len(count.m), len(count.m))
	for cc, n := range count.m {
		retries.m[cc] = retryp.Get(0, n)
	}
	conncountp.Put(count)

	for i, cmd := range multi {
		var cc conn
		if cmd.Slot() != cmds.InitSlot {
			cc = c.pslots[cmd.Slot()]
		} else {
			cc = c.pslots[last]
		}
		re := retries.m[cc]
		re.commands = append(re.commands, cmd)
		re.cIndexes = append(re.cIndexes, i)
	}
	return retries, last, false
}
```

Hope this can help you.

**Comment by wyxloading** [comment]
File a PR, check #697 

Maybe another question:
- wondering should driver auto recover from error `failed to fetch the cache because EXEC was aborted by redis or connection closed` by `DoMultiCache` during redis cluster scaling ?
