### ISSUE TITLE
Retry  `DoXCache` during redis cluster scaling

### ISSUE THREAD

**Issue by wyxloading** [redis/rueidis#700]
Recently we got `failed to fetch the cache because EXEC was aborted by redis or connection closed` by `DoMultiCache` during redis cluster scaling  ( relate to #696 )

We believe that fail reason should be something relation to cluster scaling. 
Check source below, seem like in TRANSACTION do commands `MULTI, PTTL, GET/MGET, EXEC`, then redis server return a error `MOVED {slot} {ip:port}` for `PTTL` command, and `EXEC` get a `EXECABORT` error. But driver only check with the `EXEC` command result.

https://github.com/redis/rueidis/blob/main/pipe.go#L1446-L1482

Seem like we can fix this easily, just handle previous error in TRANSACTION and let driver handle retry automaticlly.

We will test it ASAP and maybe file a PR later.

**Comment by rueian** [comment]
> just handle previous error in TRANSACTION

Do you refer to the MOVED error you mentioned? I think it’s a good idea to replace the EXECABORT with the MOVED in this case.

**Comment by wyxloading** [comment]
> Do you refer to the MOVED error you mentioned?

Yes, and `ASK` error too. Check PR #701
