### ISSUE TITLE
`DoXCache` invocation will block until slot state change from migrating to stable / moved

### ISSUE THREAD

**Issue by wyxloading** [redis/rueidis#703]
While redis cluster scaling ( add a shard ), trigger balancer to migrate slot from old shard to new shard, `DoXCache` will block until migration done.

`DoXCache` will do `askingMultiCache` and still get a `- ASK` redirection and retry again ...

Main cause is `ASKING` command should send right before sending the complete transaction. If we add a `ASKING` command before `MULTI` command instead, problem solved.

> https://redis.io/docs/latest/commands/asking/
> If an -ASK redirect is received during a transaction, only one ASKING command needs to be sent to the target node before sending the complete transaction to the target node.

```go
func askingMultiCache(cc conn, ctx context.Context, multi []CacheableTTL) *redisresults {
	commands := make([]Completed, 0, len(multi)*6)
	for _, cmd := range multi {
		ck, _ := cmds.CacheKey(cmd.Cmd)
		commands = append(commands, cmds.OptInCmd, cmds.MultiCmd, cmds.AskingCmd, cmds.NewCompleted([]string{"PTTL", ck}), Completed(cmd.Cmd), cmds.ExecCmd)
	}
	results := resultsp.Get(0, len(multi))
	resps := cc.DoMulti(ctx, commands...)
	for i := 5; i < len(resps.s); i += 6 {
		if arr, err := resps.s[i].ToArray(); err != nil {
			if preErr := resps.s[i-1].Error(); preErr != nil { // if {Cmd} get a RedisError
				err = preErr
			}
			results.s = append(results.s, newErrResult(err))
		} else {
			results.s = append(results.s, newResult(arr[len(arr)-1], nil))
		}
	}
	resultsp.Put(resps)
	return results
}
```

---

Expand from the situation above, are we able to retry a transaction if server return MOVED / ASK error ?

Nowadays driver recommends to use dedicate connection to do transaction, but it send commands to nodes that driver think that slot located. Even we handle the MOVED / ASK error, we can not send commands to the addr which error returned.

**Comment by rueian** [comment]
Thanks @wyxloading,

> Expand from the situation above, are we able to retry a transaction if server return MOVED / ASK error ?

I think the answer is yes. If the server returns a MOVED/ASK error, the transaction will be aborted and we can retry it without doubt.


> Nowadays driver recommends to use dedicate connection to do transaction, but it send commands to nodes that driver think that slot located. Even we handle the MOVED / ASK error, we can not send commands to the addr which error returned.

Why can’t we send commands to the addr where the error specified? If we can’t , then which addr we should use?

**Comment by wyxloading** [comment]
> Nowadays driver recommends to use dedicate connection to do transaction, but it send commands to nodes that driver think that slot located. Even we handle the MOVED / ASK error, we can not send commands to the addr which error returned.

Sorry, my mistake. Did not find out how to send command to target addr node earlier.

Maybe code like this ?
```go
if addr, asked := err.IsAsk(); asked {
  client.Nodes()[addr].Dedicated(...)
}
```

Are there any chance that driver can handle MOVED / ASK error for transaction automatically or with a option ?

**Comment by rueian** [comment]
Oh, do you mean our current implementation of `doresultfn` and `resultcachefn` will break transactions in the case of MOVED/ASK?

**Comment by wyxloading** [comment]
Yes. It will break transaction into single commands and retry only commands that get a MOVED/ASK error. 

For example, if we `DoMulti` with transaction commands like:
```
MULTI
SET foo bar
EXEC
```

AND `SET foo bar` command get a ASK error, it will then do `askingMulti` cause `doresultfn` append that command in `re.cAskings`. That will result in a unreasonable result cause it did not execute in a transaction.

```go
func (c *clusterClient) doretry(
	ctx context.Context, cc conn, results *redisresults, retries *connretry, re *retry, mu *sync.Mutex, wg *sync.WaitGroup, attempts int,
) {
	clean := true
	if len(re.commands) != 0 {
		resps := cc.DoMulti(ctx, re.commands...)
		clean = c.doresultfn(ctx, results, retries, mu, cc, re.cIndexes, re.commands, resps.s, attempts)
		resultsp.Put(resps)
	}
	if len(re.cAskings) != 0 {
		resps := askingMulti(cc, ctx, re.cAskings)
		clean = c.doresultfn(ctx, results, retries, mu, cc, re.aIndexes, re.cAskings, resps.s, attempts) && clean
		resultsp.Put(resps)
	}
	if clean {
		retryp.Put(re)
	}
	wg.Done()
}
```

For transaction, i think users MUST use dedicate client to send commands ( assuming dedicate client will only retry commands all or nothing ). 
Further more, dedicate client did not handle MOVED / ASK error, so users should handle that kind of error themselves. That's why i mention that maybe driver can handle MOVED / ASK error automatically or with a option.

**Comment by rueian** [comment]
@wyxloading, this is actually a new issue after https://github.com/redis/rueidis/pull/697 where we removed the old doMulti, the function which originally handled transactions.

I think there is nothing to do with the dedicated connections and we should just fix the doresultfn, letting it not break the transaction but retrying the full command slice to the address provided by the MOVED or ASK response.

**Comment by rueian** [comment]
We need to do find out if a MOVED/ASK response is in the middle of a MULTI/EXEC block after this line: https://github.com/redis/rueidis/blob/3b9473a103aaa81aa8f88fc5a789e6a4abe3474e/cluster.go#L665

Then we should put the whole transaction back into the `nr`.

@wyxloading please let me know if you are interested in this fix.
